// Evidence-led portfolio curation. Null dates are never replaced by article dates.
import {escapeHtml as esc} from './writing-architecture.mjs';
export const talkCategories = ['Invited Talks & Professional Education', 'Conference Presentations', 'Workshops & Clinical Education', 'Public Engagement'];
export const talks = [
  {id:'vrilo-2026', title:'VR curriculum integration and the seven-step VRILO pathway', event:'International Postgraduate Conference and Research Forum 2026', host:'The Education University of Hong Kong', date:'2026', location:null, format:'Conference presentation', role:'Presenter', category:talkCategories[1], description:'A reflection on moving virtual reality from novelty towards purposeful and sustainable curriculum integration.', links:[['Read the related reflection','posts/why-universities-are-attracted-to-vr-and-why-novelty-is-not-enough.html']], image:null, status:'Completed', verification:'DELIVERY VERIFIED — article 322 explicitly states “I presented”. Year/event/host supported; exact date, venue and formal presentation title require confirmation. Public title is a descriptive summary.', source:'article-content.mjs: English article 322; generate-site.mjs: image caption 322'},
  {id:'student-outreach', title:'Speaking with prospective physiotherapy students and parents', event:'Student and parent information session', host:null, date:null, location:'Hong Kong', format:'Public engagement', role:'Speaker representing Saint Francis University and the School of Health Sciences', category:talkCategories[3], description:'A programme-information conversation about educational choices and the uncertainty surrounding HKDSE results.', links:[['Read the outreach reflection','posts/waiting-for-results-reflections-on-speaking-to-hong-kongs-future-physiotherapy-students.html']], image:null, status:'Completed', verification:'DELIVERY VERIFIED — article 310 describes representing the university and addressing students/parents; exact date, event title and organiser require confirmation.', source:'article-content.mjs: English article 310; generate-site.mjs: image alt 310'},
  {id:'pan-pacific-2025', title:'Presentation at the 14th Pan Pacific Conference on Rehabilitation', event:'14th Pan Pacific Conference on Rehabilitation', host:null, date:null, dateLabel:'8–9 November 2025 (conference dates; individual session date not recorded)', location:null, format:'Conference presentation', role:'Presenter', category:talkCategories[1], description:'A conference presentation documented in the existing professional Media record. The formal talk title and topic are not yet recorded.', links:[['View the existing presentation record','https://www.instagram.com/yutakwing002/p/DaxgoRDlIme/']], image:null, status:'Completed', verification:'DELIVERY VERIFIED — existing Media item explicitly identifies a presentation and event dates. Formal talk title, topic, host and venue require confirmation; social post date is not the event date.', source:'experience-content.mjs: English media.instagramItems'},
];
export const unverifiedTalks = [
  {title:'End-of-lecture content-mastery quizzes', source:'practice-note-content.mjs: article 325', verification:'VERIFICATION REQUIRED — presentation is supported, but event, category, date and venue are not established; withheld from archive.'},
  {title:'World Physiotherapy Congress 2025, Tokyo', source:'extended-practice-note-content.mjs: article 328', verification:'VERIFICATION REQUIRED — attendance is explicit; do not infer a specific presentation from generic discussion of presenting.'},
  {title:'Thinking with AI, Not Just About AI', source:'blog-ii-article-content.mjs: article 333', verification:'VERIFICATION REQUIRED — conference reflection is not sufficient evidence of a delivered talk.'},
];
export const academicCv = {href:null, reviewedOn:null, status:'CURRENT CV REQUIRED'};
export const educatorResources = [
  {title:'Clinical-reasoning activity planner', source:'posts/beyond-the-right-answer-why-we-should-ask-students-to-explain.html'},
  {title:'Responsible AI assessment/task template', source:'posts/movement-science-assessment-redesign-for-generative-ai.html'},
  {title:'VR implementation checklist', source:'posts/why-universities-are-attracted-to-vr-and-why-novelty-is-not-enough.html'},
  {title:'Mini Skills OSPE station template', source:'goniometry/'},
].map(item=>({...item,status:'TAK WING APPROVAL REQUIRED',href:null}));
export const portfolioMetadata = {
 research:['AI, VR & Physiotherapy Education Research | Tak Wing Yu','Explore Tak Wing Yu’s research on AI-supported clinical reasoning, virtual reality, simulation and physiotherapy education, with publications and project status.'],
 teaching:['Physiotherapy Teaching & Assessment | Tak Wing Yu','Explore Tak Wing Yu’s teaching philosophy, assessment designs, simulation work and purposeful use of AI and VR in physiotherapy education.'],
 media:['Talks, Presentations & Media | Tak Wing Yu','Selected talks and presentations by Tak Wing Yu, with source-linked reflections, a short teaching showcase and professional moments.'],
 resources:['Educator Resources | Tak Wing Yu','Educator resource development, reflective writing and routes into the Skills Lab. Proposed templates are clearly separated from available learning activities.'],
 collaborate:['Research & Teaching Collaboration | Tak Wing Yu','Connect with Tak Wing Yu about physiotherapy education research, AI, virtual reality, simulation and teaching collaborations.'],
};
export const translationNotice = locale => locale==='en' ? '' : '<p class="translation-note" lang="en">TRANSLATION REQUIRED — this new academic portfolio section is currently in English.</p>';
export function renderTalks(locale) {
 return `<section class="section-block" id="talks" lang="en"><h2>Talks &amp; Presentations</h2><p>A selected speaking archive linked to first-person records. Descriptive titles are used where the formal programme title is not recorded; missing event details are stated explicitly.</p>${translationNotice(locale)}<nav class="talk-category-nav" aria-label="Talk categories">${talkCategories.map((c,i)=>`<a href="#talk-category-${i}">${esc(c)}</a>`).join('')}</nav>${talkCategories.map((category,i)=>`<section id="talk-category-${i}" class="section-block"><h3>${esc(category)}</h3>${talks.filter(t=>t.category===category).map(t=>`<article class="publication-card"><p class="eyebrow">${t.status}</p><h4>${esc(t.title)}</h4>${t.image ? `<img src="${locale === "en" ? "./" : "../"}${esc(t.image.src)}" alt="${esc(t.image.alt)}" width="${t.image.width}" height="${t.image.height}" loading="lazy" />` : ""}<p>${esc(t.event)}${t.host ? ` · ${esc(t.host)}` : ''}</p><dl><dt>Date</dt><dd>${t.dateLabel || (t.date ? `${t.date} — exact date not recorded` : 'Exact date not recorded')}</dd><dt>Location / format</dt><dd>${esc(t.location || 'Venue not recorded')} · ${esc(t.format)}</dd><dt>Speaking role</dt><dd>${esc(t.role)}</dd></dl><p>${esc(t.description)}</p>${t.links.map(([label,href])=>`<a class="secondary-link" href="${href.startsWith("https://") ? href : "./"+href}">${esc(label)}</a>`).join(' ')}</article>`).join('') || '<p>No verified entries published in this category yet.</p>'}</section>`).join('')}</section>`;
}
export function renderEducatorResources(locale) {
 return `<section id="educator-tools" class="section-block" lang="en"><h2>Educator tools in development</h2><p>These are proposed resource formats, not finished templates or clinical guidance. Each needs Tak Wing’s content review before release.</p>${translationNotice(locale)}<div class="resource-grid">${educatorResources.map(r=>`<article><p class="eyebrow">In development · Approval required</p><h3>${esc(r.title)}</h3><p>No downloadable material is available yet.</p><a href="${r.source.includes('goniometry/') ? (locale==='en'?'./':'../') : './'}${r.source}">Explore the existing ${r.source.includes('goniometry/')?'Goniometry practice hub':'related writing'}</a></article>`).join('')}</div></section>`;
}
