import {expandedModules, principles, capstoneSteps, exerciseExamples} from './course-curriculum.mjs';
import {escapeHtml as esc} from './writing-architecture.mjs';

// Original course outline supplied by the owner, 10 October 2026.
// Development status is deliberate: no enrolment, accreditation, duration or pricing metadata.
export const courseFile = 'course-applied-ai-allied-health';
export const courseTitle = 'Applied AI for Allied Health Professionals';
export const courseSubtitle = 'From Clinical Problems to Working Prototypes';
export const courseDescription = 'A developing practical course by Tak Wing Yu helping allied health professionals move from clinical problems to AI prototypes using computer vision, movement analysis, validation and responsible implementation.';
export const coursesDescription = 'Research-informed courses and workshops by Tak Wing Yu on AI, clinical reasoning, virtual reality, simulation and allied health education.';
export const courseContact = './contact.html?subject=Applied%20AI%20for%20Allied%20Health%20Professionals#contact-form';
const list = items => `<ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`;
const status = '<span class="evidence-status">IN DEVELOPMENT</span>';
const local = (locale,en,tc,sc) => locale==='zh-hant'?tc:locale==='zh-hans'?sc:en;
export const coursesLabel = locale => local(locale,'Courses','課程','课程');
export const coursesHeading = locale => local(locale,'Courses & Workshops','課程及工作坊','课程及工作坊');
export const translationNotice = locale => local(locale,'','中文課程介紹正在準備中。專業術語及內容將經人工審閱；目前請參閱英文課程概念。課程仍在開發中。','中文课程介绍正在准备中。专业术语及内容将经人工审阅；目前请参阅英文课程概念。课程仍在开发中。');
export const courseModules = expandedModules;
const outcomes = [
 'Identify a meaningful allied health problem that may benefit from AI.',
 'Translate a clinical need into measurable technical requirements.',
 'Explain how basic computer vision represents human movement.',
 'Distinguish raw AI output from clinically meaningful interpretation.',
 'Read and adapt simple Python-based movement-analysis workflows.',
 'Use basic computer-vision and pose-estimation tools.',
 'Convert body landmarks into simple clinical movement measures.',
 'Explain the role and limitations of musculoskeletal modelling.',
 'Develop an early allied health AI prototype.',
 'Critically evaluate reliability, validity and clinical utility.',
 'Identify important privacy, safety and bias considerations.',
 'Communicate effectively with technical collaborators while retaining clinical oversight.'
];
export const technologies = ['Python','OpenCV','MediaPipe','NumPy','SciPy','pandas','Matplotlib','OpenSim','AI-assisted coding tools'];
const pathway = (items,label) => `<ol class="course-pathway" aria-label="${esc(label)}">${items.map(([title,detail],i)=>`<li><span class="course-step" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><strong>${esc(title)}</strong>${detail?`<span>${esc(detail)}</span>`:''}</li>`).join('')}</ol>`;
const moduleHtml = (module,i) => `<details class="course-module" id="module-${i+1}"${[0,8].includes(i)?' open':''}><summary><span class="course-module-number">Module ${i+1}</span><h3>${esc(module.title)}</h3><span class="course-module-question">${esc(module.question)}</span><span class="course-module-toggle" aria-hidden="true">+</span></summary><div class="course-module-body">${list(module.topics)}${module.body}<p class="course-activity"><strong>Practical activity</strong><br>${esc(module.activity)}</p></div></details>`;
const cta = () => `<section class="section-block course-pilot" id="pilot"><p class="eyebrow">Collaboration</p><h2>Interested in piloting this course?</h2><p>I am interested in collaborating with universities, professional associations, allied health departments and clinical organisations to pilot and evaluate this programme.</p><p>Potential collaborations may include:</p>${list(['Invited workshops','Faculty development','Clinician training','Postgraduate learning','Interdisciplinary AI-development workshops','Collaborative educational research'])}<div class="hero-actions"><a class="primary-link" href="${courseContact}">Discuss a pilot or workshop</a><a class="secondary-link" href="./research.html#ai-literacy">Explore my research</a></div></section>`;

export function courseLandingBody() {
 return `<article class="portfolio-subpage courses-page"><section class="pilot-page-hero"><p class="eyebrow">Professional learning</p><h1>Courses &amp; Workshops</h1><p class="course-subtitle">Research-informed professional learning for health professions education and allied health practice.</p><p>My courses and workshops translate questions emerging from teaching, research and educational development into practical professional learning.</p><p>The emphasis is not on adopting technology for novelty. Each programme begins with a meaningful educational or clinical problem, examines where technology may add value, and considers how the resulting approach can be evaluated responsibly.</p><p>Programmes may be offered as short courses, workshops, invited faculty-development sessions or collaborative pilots.</p><p class="eyebrow">Research-informed · Practice-oriented · Build something useful</p></section>
 <section class="section-block course-featured"><p class="eyebrow">Featured course concept</p><article class="publication-card">${status}<h2>${courseTitle}</h2><p class="course-subtitle">${courseSubtitle}</p><p>A practice-oriented introduction to defining, prototyping and evaluating AI-enabled tools for allied health practice.</p><dl class="course-facts"><div><dt>Audience</dt><dd>Allied health clinicians, educators and researchers</dd></div><div><dt>Level</dt><dd>Introductory to intermediate</dd></div><div><dt>Coding</dt><dd>No previous programming experience required</dd></div><div><dt>Focus</dt><dd>Clinical problem definition · Computer vision · Movement analysis · Prototyping · Validation · Responsible AI</dd></div></dl><a class="primary-link" href="./${courseFile}.html">Explore course concept <span aria-hidden="true">→</span></a></article></section>
 <section class="section-block"><h2>In the laboratory</h2><p>These are developing ideas for professional learning, not programmes currently open for registration.</p><div class="scholarship-grid">${[
 ['AI Literacy for Health Professions Educators','Teaching, Assessment and Responsible Use','CONCEPT','Practical AI literacy for educators responsible for teaching, assessment and professional preparation.'],
 ['Designing AI for Clinical Reasoning','Without Turning AI Into the Shortcut','IN DEVELOPMENT','Designing AI-supported learning that questions, challenges and makes learner reasoning visible rather than replacing it.'],
 ['Designing VR for Health Professions Education','From Headset to Curriculum','WORKSHOP CONCEPT','Moving beyond technological novelty to align immersive learning with curriculum, assessment, facilitation and sustainable implementation.']
 ].map(([title,subtitle,state,description])=>`<article><span class="evidence-status">${state}</span><h3>${title}</h3><p><strong>${subtitle}</strong></p><p>${description}</p></article>`).join('')}</div></section><p><a class="secondary-link" href="${courseContact}">Discuss a course or workshop</a></p></article>`;
}

export function courseDetailBody() {
 const roles=['Functional coding literacy.','Camera and image/video processing.','Markerless pose estimation.','Coordinate and vector calculations.','Signal processing and filtering.','Data organisation.','Visualisation.','Musculoskeletal modelling.','Supporting code development, explanation and debugging.'];
 return `<article class="portfolio-subpage courses-page"><section class="pilot-page-hero" id="overview"><p class="eyebrow"><a href="./courses.html">Courses &amp; Workshops</a></p>${status}<h1>${courseTitle}</h1><p class="course-subtitle">${courseSubtitle}</p><p class="course-principle"><strong>Start with the clinical problem — not the technology.</strong></p><p>Artificial intelligence is increasingly entering rehabilitation and allied health practice, but clinicians do not need to become software engineers to participate meaningfully in its development.</p><p>This developing course introduces allied health professionals to the practical foundations of AI-enabled movement analysis, computer vision and open-source biomechanics.</p><p>The emphasis is not on learning programming for its own sake. Instead, participants develop enough technical literacy to define clinical requirements, understand what AI systems are measuring, participate in development, build simple prototypes and critically evaluate whether an output is clinically meaningful.</p><p>The course follows a simple question:</p><p><strong>I have a clinical problem. How can I turn it into an AI-enabled tool — and how do I know whether I can trust it?</strong></p><nav class="course-jump-links" aria-label="Course sections">${[['overview','Overview'],['principles','Principles'],['journey','Modules'],['practical','Practical Work'],['capstone','Capstone'],['outcomes','Outcomes'],['delivery','Delivery'],['pilot','Pilot']].map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav></section>
 <section class="section-block" id="audience"><h2>Who is this for?</h2><p>The course is intended for allied health professionals, educators and researchers interested in participating more meaningfully in the design, evaluation or implementation of AI-enabled clinical tools.</p>${list(['Physiotherapists','Occupational therapists','Rehabilitation professionals','Sports and exercise practitioners','Allied health educators','Clinical researchers','Postgraduate students working in rehabilitation or movement science','Clinicians collaborating with software, engineering or data-science teams'])}<p><strong>Prior coding experience: Not required.</strong></p><p>Participants are not expected to become software engineers. Programming is introduced only to the level needed to understand, modify, test and critically evaluate simple AI workflows.</p></section>

 <section class="section-block" id="principles"><h2>Five Principles</h2><ol class="course-principles">${principles.map(([title,body],i)=>`<li><span class="course-step" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><h3>${title}</h3><p>${body}</p></li>`).join('')}</ol></section>
 <section class="section-block course-process"><h2>From clinical need to responsible implementation</h2>${pathway(['Clinical Problem','Define What AI Should Do','Understand the Data','Capture Movement','Detect Human Pose','Calculate Clinical Measures','Prototype','Validate','Implement Responsibly'].map(x=>[x,'']),'Overall course journey')}</section>
 <section class="section-block" id="journey"><h2>Course Journey</h2><p>Ten proposed modules connect clinical questions, practical experimentation and critical evaluation. Each summary states the question; open a module to explore its topics and activities.</p><div class="course-modules">${courseModules.map(moduleHtml).join('')}</div></section>
 <section class="section-block" id="practical"><h2>What Participants Will Build</h2><p>Proposed exercises may change during pilot development. These are educational activities, using safe sample data or appropriately consented recordings.</p><ol class="course-exercises">${exerciseExamples.map((x,i)=>`<li><span class="course-step">Exercise ${i+1}</span><p>${x}</p></li>`).join('')}</ol></section>
 <section class="section-block course-capstone" id="capstone"><p class="eyebrow">Capstone project</p><h2>Capstone — From Your Clinical Problem to a Prototype</h2><p>Return to the problem selected in Module 1, working individually or in a small interdisciplinary group. Develop an early demonstrator where feasible, supported by an explicit validation and implementation plan.</p>${pathway(['Clinical Problem','Intended Measure','Data','AI Method','Prototype','Clinical Interpretation','Validation','Responsible Implementation'].map(x=>[x,'']),'Capstone process')}<ol class="course-capstone-steps">${capstoneSteps.map(([title,body])=>`<li><h3>${title}</h3><p>${body}</p></li>`).join('')}</ol></section>
 <section class="section-block" id="outcomes"><h2>By the end of the course, participants should be able to:</h2><ol class="course-outcomes">${outcomes.map(x=>`<li>${x}</li>`).join('')}</ol></section>
 <section class="section-block"><h2>Technologies Explored</h2><ul class="course-tools">${technologies.map((x,i)=>`<li><strong>${x}</strong><span>${roles[i]}</span></li>`).join('')}</ul><p>The course focuses on transferable principles. Specific software may change as the field evolves.</p><p class="course-sources">Technical background: <a href="https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker?hl=en">MediaPipe pose landmark documentation</a> · <a href="https://opensimconfluence.atlassian.net/wiki/spaces/OpenSim/pages/53089741/Tutorial%2B3%2B-%2BScaling%2C%2BInverse%2BKinematics%2C%2Band%2BInverse%2BDynamics">OpenSim modelling tutorial</a>.</p></section>
 <section class="section-block" id="delivery"><h2>Possible Delivery Formats</h2><dl class="course-facts">${[['Intensive workshop','Hands-on introduction and prototype experience.'],['Short professional course','Multiple sessions allowing progressive development.'],['Faculty development','For allied health educators and researchers.'],['Postgraduate workshop','For MSc/PhD students interested in digital rehabilitation and movement research.'],['Interdisciplinary development workshop','Bring allied health professionals together with engineers, computer scientists, designers and data scientists.']].map(([t,d])=>`<div><dt>${t}</dt><dd>${d}</dd></div>`).join('')}</dl><p>Interdisciplinary development is particularly valuable because clinicians understand the clinical problem while technical collaborators understand how to build the system.</p></section>
 <section class="section-block course-development" id="development"><h2>Course status</h2>${status}<p>This course is currently being developed and will be refined through pilot delivery, participant feedback and evaluation.</p><h3>Current development priorities</h3>${list(['Build beginner-friendly notebooks','Prepare demonstration videos','Create safe sample datasets','Develop validation exercises','Test capstone activities','Refine responsible-AI content','Pilot with allied health clinicians and/or educators'])}</section>
 ${cta()}<p class="course-acknowledgement"><em>The development of this course concept has been informed by contemporary work in open-source computer vision, biomechanics and clinician-led AI development in rehabilitation. The educational framework and website diagrams are original adaptations; no endorsement by external presenters or software developers is implied.</em></p><p class="course-disclaimer">Course prototypes are educational tools and should not be used for clinical diagnosis or patient-management decisions without appropriate validation, governance and regulatory review.</p></article>`;
}

export function coursePlaceholderBody(locale,detail=false) {
 const english=detail?courseFile:'courses';
 return `<article class="portfolio-subpage courses-page"><section class="pilot-page-hero"><p class="eyebrow">${coursesHeading(locale)}</p><h1${detail?' lang="en"':''}>${detail?courseTitle:coursesHeading(locale)}</h1><p class="course-principle">${translationNotice(locale)}</p><p lang="en">${status} ${detail?courseSubtitle:'Research-informed professional learning for health professions education and allied health practice.'}</p><p><a class="primary-link" href="../${english}.html" hreflang="en">${local(locale,'Read the English course concept','閱讀英文課程概念','阅读英文课程概念')}</a></p><a class="secondary-link" href="./${detail?'courses':'course-applied-ai-allied-health'}.html">${detail?coursesHeading(locale):`<span lang="en">${courseTitle}</span>`}</a></section></article>`;
}
export function courseTeaser(locale) {
 return `<aside class="course-home-teaser" aria-labelledby="course-teaser-title"><p class="eyebrow">${coursesHeading(locale)}</p><div lang="en"><span class="evidence-status">IN DEVELOPMENT</span><h2 id="course-teaser-title">${courseTitle}</h2><p><em>${courseSubtitle}</em></p>${locale==='en'?'<p>A developing professional course exploring how allied health professionals can define clinical AI requirements, understand computer vision, develop simple prototypes and critically evaluate whether AI outputs are safe and clinically meaningful.</p>':''}</div>${locale==='en'?'':`<p>${translationNotice(locale)}</p>`}<a class="secondary-link" href="./${courseFile}.html">${local(locale,'Explore the course','查看課程概念','查看课程概念')} <span aria-hidden="true">→</span></a></aside>`;
}
export function courseContextLink(locale,kind) {
 const label=kind==='research'?local(locale,'Explore related course','查看相關課程','查看相关课程'):coursesHeading(locale);
 return `<p class="course-context-link"><a class="secondary-link" href="./${kind==='research'?courseFile:'courses'}.html">${label} <span aria-hidden="true">→</span></a></p>`;
}
export function courseSearchEntries(locale) {
 const notice=translationNotice(locale);
 return [
 {title:coursesHeading(locale),href:'./courses.html',description:notice||coursesDescription,category:'Courses & Workshops',content:coursesDescription+' '+courseTitle},
 {title:`AI course: ${courseTitle}`,href:`./${courseFile}.html`,description:notice||courseDescription,category:'Course concept · In development',content:[courseTitle,courseSubtitle,'clinical AI allied health course computer vision movement analysis',...technologies,...courseModules.flatMap(m=>[m.title,m.question,...m.topics]),...outcomes].join(' ')}
 ];
}
