export const experienceContent = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      research: "Research",
      teaching: "Teaching",
      writing: "Writing",
      media: "Media",
      resources: "Resources",
      collaborate: "Collaborate with me",
    },
    home: {
      eyebrow: "A public academic laboratory",
      name: "Tak Wing Yu",
      role: "Senior Lecturer in Physiotherapy",
      disciplines: "Physiotherapist · Educator · Researcher · Learning Designer",
      title: "Designing better ways to learn clinical reasoning through AI, virtual reality, and simulation.",
      identity: "I explore how emerging technologies can support critical thinking, experiential learning, and practice readiness in health professions education—without replacing the human judgement at the centre of clinical care.",
      lede: "My work begins with an educational problem, then asks whether technology can make thinking more visible, practice more meaningful, or feedback more useful.",
      actions: ["Explore the laboratory", "View featured work", "About me", "Collaborate with me"],
      credibilityEyebrow: "Grounded in practice",
      credibility: [
        ["2026", "Teaching Excellence Award", "Faculty-level recognition following a 2025 nomination."],
        ["AI · VR · Simulation", "Educational focus", "Designed around clinical reasoning and practice readiness."],
        ["Design-based research", "Research approach", "Iterative development, evaluation, and honest refinement."],
        ["Hong Kong · South Africa", "Academic perspective", "Physiotherapy education across different contexts."],
      ],
      nowEyebrow: "Working now",
      nowTitle: "What I am exploring, building, testing, and learning",
      nowIntro: "A live view of the questions currently shaping my teaching and research.",
      now: [
        ["Exploring", "Making reasoning visible", "How AI can reveal student thinking without becoming a clinical shortcut.", "Research", "research", "ai-literacy"],
        ["Building", "A questioning chatbot", "A clinical-reasoning tool centred on safety screening and learner explanation.", "Development", "research", "reasoning-chatbot"],
        ["Testing", "Immersive practice", "How VR can support acupuncture, anatomy, and movement science.", "Pilot", "research", "vr-acupuncture"],
        ["Learning", "Sustainable implementation", "What useful adoption requires beyond purchasing a new platform.", "Writing", "writing", ""],
      ],
      projectsEyebrow: "Featured work",
      projectsTitle: "Evidence of the laboratory in practice",
      projectsIntro: "Selected projects show the educational problem, the designed response, my role, and the current status without overstating what is known.",
      projectLabels: { problem: "Problem", approach: "Approach", role: "My role", status: "Status", action: "Explore project" },
      flagshipEyebrow: "Flagship work",
      flagshipTitle: "Three questions shaping my work",
      flagshipIntro: "Each strand begins with a learning problem. Technology is used only when it creates better opportunities to reason, practise, receive feedback, and prepare for clinical responsibility.",
      flagshipLabels: { problem: "Educational problem", approach: "Pedagogical approach", pathway: "Learning sequence", status: "Evidence status" },
      flagships: [
        ["AI-supported clinical reasoning", "How can learners explain, challenge, and revise their reasoning before fluent AI output hides uncertainty?", "I use AI as a Socratic thinking partner: students reason first, then question, verify, revise, and justify their judgement.", "Reason → Question → Challenge → Revise → Justify", "PILOT", "research", "reasoning-chatbot", "Explore AI and reasoning"],
        ["VR for purposeful immersive learning", "How can learners safely rehearse spatial, embodied, or difficult-to-access experiences without confusing novelty with learning?", "I align immersion with a defined learning outcome, preparation, guided practice, feedback, and debriefing.", "See → Explore → Practise → Repeat", "IN DEVELOPMENT", "research", "vr-acupuncture", "Explore VR work"],
        ["Simulation and practice readiness", "How can students rehearse decisions and professional responsibility before the complexity of clinical placement?", "I design structured scenarios, role rotation, observation, feedback, and reflection around authentic practice decisions.", "Rehearse → Decide → Receive feedback → Adapt", "ONGOING STUDY", "research", "simulation-role-rotation", "Explore simulation work"],
      ],
      connectionEyebrow: "How the work connects",
      connectionTitle: "From preparation to clinical responsibility",
      connectionIntro: "The strands are not separate technologies. They form a learning pathway towards safer, more accountable professional judgement.",
      connectionSteps: [
        ["Virtual reality", "See, experience, and practise"],
        ["Artificial intelligence", "Reason, question, and challenge"],
        ["Simulation", "Rehearse, receive feedback, and adapt"],
        ["Clinical placement", "Transfer learning and take responsibility"],
      ],
      connectionClosing: "Technology prepares. Clinical experience makes the learning real.",
      experienceEyebrow: "Experience the work",
      experienceTitle: "Learn by doing, not only by reading",
      experienceIntro: "Explore selected ideas through short interactive activities about clinical reasoning, artificial intelligence, virtual reality, and simulation.",
      experiences: [
        ["Clinical Readiness Lab", "A top-down interactive learning experience exploring AI, VR, and simulation in health professions education.", "clinical-readiness-lab.html", "Enter the lab", "Interactive lab"],
        ["Reasoning Runner", "Escape unsafe AI claims by spotting red flags, checking evidence, and choosing the safer clinical response.", "reasoning-runner.html", "Play Reasoning Runner", "Interactive challenge"],
        ["AI Literacy Check", "A reflective knowledge check on verification, privacy, bias, disclosure, and professional responsibility.", "ai-literacy-check.html", "Take the check", "15 questions"],
      ],
      impactEyebrow: "Selected milestones",
      impactTitle: "Recognition grounded in the work",
      impactIntro: "A concise record of teaching, scholarship, and educational development already documented across this portfolio.",
      impact: [
        ["Teaching Excellence Award, 2026", "Faculty-level recognition for student-centred teaching, curriculum development, and purposeful educational innovation.", "writing", "two-years-in-hong-kong-reflecting-on-teaching-innovation-and-receiving-a-teaching-excellence-award"],
        ["Published VR education research", "Peer-reviewed work examining educators’ perspectives on immersive virtual reality in health professions education.", "research", "publications"],
        ["VR acupuncture development", "A curriculum-aligned learning application with training, practice, and assessment modes.", "research", "vr-acupuncture"],
        ["Simulation role-rotation research", "Ongoing analysis of what students may learn as clinicians, peer patients, observers, and peer debriefers.", "research", "simulation-role-rotation"],
      ],
      snapshotsEyebrow: "Inside the classroom",
      snapshotsTitle: "Teaching snapshots",
      snapshotsIntro: "Small examples of how educational philosophy becomes something students can actually do.",
      writingEyebrow: "Behind the design",
      writingTitle: "Latest writing",
      writingIntro: "Recent reflections on the decisions, tensions, limitations, and occasional failures behind educational innovation.",
      writingAction: "Read article",
      writingAll: "Explore all writing",
      collaborateEyebrow: "Collaboration",
      collaborateTitle: "Collaborate with me",
      collaborateIntro: "I welcome opportunities to collaborate on research, teaching innovation, curriculum development, and educational technology in health professions education.",
      collaborationThemes: ["AI and clinical reasoning", "Virtual reality curriculum integration", "Simulation and clinical education", "Educational research"],
      collaborationActions: ["Discuss a research project", "Invite me to speak", "Explore a teaching collaboration"],
      invitationTitle: "This is a laboratory, not an archive.",
      invitationText: "Projects evolve, questions change, and useful resources are shared as they become ready. The aim is to make the process of educational design visible.",
    },
    story: {
      eyebrow: "My journey",
      title: "From movement to meaning",
      intro: "My work has moved from understanding how people move, to asking how future physiotherapists learn to think, decide, and care.",
      chapters: [
        ["Why physiotherapy", "Physiotherapy first attracted me because it joins scientific understanding with practical human judgement. Movement can be measured, but good care still depends on listening, reasoning, adapting, and seeing the person rather than only the condition."],
        ["Why education", "Teaching made the hidden work of clinical reasoning impossible to ignore. Students did not only need more information; they needed opportunities to explain decisions, test assumptions, make mistakes safely, and connect theory with the person in front of them."],
        ["Why virtual reality", "VR offered a way to make difficult, spatial, or rarely encountered experiences more available. My interest is not in immersion for its own sake. It is in whether a designed experience helps students notice, practise, and understand something that other methods cannot show as clearly."],
        ["Why artificial intelligence", "AI raises a different challenge. It can expand feedback and generate possibilities, but it can also hide weak reasoning behind fluent answers. I am interested in designs that make students think before consulting AI, question what it produces, and remain accountable for the final judgement."],
      ],
      philosophyTitle: "The problem I am trying to solve",
      philosophy: "How can we design learning experiences that make clinical reasoning visible, preserve meaningful human judgement, and use technology only where it adds genuine educational value?",
      principles: [
        ["Start with the learner", "Define the competence, misconception, or barrier before choosing a tool."],
        ["Make thinking visible", "Ask students to explain, compare, defend, and revise their decisions."],
        ["Design for transfer", "Connect classroom activity to the uncertainty and responsibility of professional practice."],
        ["Evaluate honestly", "Treat friction, failure, and unintended consequences as evidence for the next design."],
      ],
    },
    projects: {
      eyebrow: "Signature work",
      title: "Featured projects",
      intro: "These projects bring together physiotherapy, AI, VR, simulation, and educational design around one goal: improving how students develop and demonstrate clinical reasoning.",
      knownFor: "I want to be known for designing evidence-informed ways to integrate AI and VR into physiotherapy education without allowing technology to replace the thinking students must learn to do.",
      labels: { problem: "The problem", design: "Design response", learning: "What learners practise", status: "Current status", next: "Next question" },
    },
    ideas: {
      eyebrow: "Open notebook",
      title: "Ideas in motion",
      intro: "Questions, experiments, and influences that are still developing. They are shared here because academic thinking is more useful when its unfinished edges remain visible.",
      workingTitle: "What I am working on",
      workingIntro: "Updated for July 2026",
      questionsTitle: "Questions on the workbench",
      readingEyebrow: "Reading",
      readingCardLabel: "Reading around",
      readingTitle: "Currently reading around",
      visionTitle: "Vision 2030",
      vision: "By 2030, the most useful educational technologies will not be the most spectacular. They will be the ones that make reasoning more visible, practice more accessible, feedback more timely, and professional responsibility harder to avoid.",
      working: [
        "AI-supported safety screening and clinical reasoning",
        "VR-supported acupuncture learning and assessment",
        "Making learner reasoning visible in technology-enhanced tasks",
        "Movement analysis and technology-supported rehabilitation",
      ],
      questions: [
        "When does AI feedback deepen reasoning, and when does it quietly replace it?",
        "What should remain deliberately AI-free in a physiotherapy curriculum?",
        "How much immersion is educationally useful before cognitive load becomes a barrier?",
        "How can students show the reasoning behind a technically correct answer?",
      ],
      reading: [
        ["Situated learning", "How participation, context, and professional community shape learning."],
        ["Design-based research", "How iterative design can produce both practical improvement and transferable knowledge."],
        ["AI in medical education", "What current evidence says about learning, assessment, governance, and professional responsibility."],
      ],
    },
    resources: {
      eyebrow: "Useful things",
      title: "Resources for educators",
      intro: "Practical tools and design prompts shared when they are ready to use. Developing material is labelled clearly rather than presented as finished.",
      available: "Available now",
      developing: "In development",
      items: [
        ["Reasoning Runner", "A playful clinical-reasoning challenge about evidence, red flags, verification, and unsafe AI claims.", "reasoning-runner.html", "Play the game"],
        ["Clinical Readiness Lab", "Explore AI, VR, and simulation through three interactive learning stations.", "clinical-readiness-lab.html", "Enter the lab"],
        ["Goniometry Skills Lab", "Six interactive mini-OSPE activities for practising landmark identification and goniometer placement across the upper and lower limbs.", "goniometry", "Enter the lab"],
        ["Elbow Goniometry Challenge", "Practise positioning a goniometer for elbow extension by aligning its axis, stationary arm, and moving arm with anatomical landmarks.", "elbow-goniometry", "Start the challenge"],
        ["Ankle Goniometry Challenge", "Practise measuring ankle dorsiflexion by aligning a goniometer with the lateral malleolus, fibular head, and fifth metatarsal.", "ankle-goniometry", "Start the challenge"],
        ["Shoulder Goniometry Challenge", "Practise measuring standing shoulder flexion and extension by aligning a goniometer with the lateral humeral head, mid-axillary line, and lateral epicondyle.", "shoulder-goniometry", "Start the challenge"],
        ["Shoulder Rotation Goniometry Challenge", "Practise measuring supine shoulder internal and external rotation in a lateral view using the olecranon, a vertical reference, and the ulnar styloid.", "shoulder-rotation-goniometry", "Start the challenge"],
        ["Hip Goniometry Challenge", "Practise measuring hip flexion and extension by aligning a goniometer with the greater trochanter, lateral pelvic midline, and lateral femoral midline towards the lateral epicondyle.", "hip-goniometry", "Start the challenge"],
        ["Knee Goniometry Challenge", "Practise measuring knee flexion by aligning the goniometer with the lateral femoral epicondyle, greater trochanter, and lateral malleolus.", "knee-goniometry", "Start the challenge"],
        ["Cardiorespiratory Skills Lab", "Five interactive formative activities for auscultation placement, chest expansion, percussion-site selection, and respiratory-rate observation.", "cardiorespiratory", "Enter the lab"],
        ["AI Literacy Check", "A 15-question reflective activity on verification, privacy, bias, and responsible use.", "ai-literacy-check.html", "Open activity"],
        ["Typing Speed Test", "A simple 60-second test of typing speed and accuracy using common English and health-professions vocabulary.", "typing-test", "Take the test"],
        ["Academic Notes Library", "Connected notes on education, technology, physiotherapy, and research.", "notes.html", "Browse notes"],
        ["Writing archive", "Reflections and public scholarship organised by physiotherapy, AI, and professional reflection.", "writing.html", "Read writing"],
      ],
      developingItems: [
        ["Clinical-reasoning activity planner", "A prompt set for aligning a case, learner decision, evidence, feedback, and assessment."],
        ["VR implementation checklist", "Questions for curriculum fit, accessibility, learner preparation, technical support, and evaluation."],
        ["Responsible AI task template", "A structure for defining permitted AI use and the evidence students must still produce themselves."],
      ],
      promptTitle: "A design prompt to use today",
      prompt: "Before adding technology, write down: the competence students must demonstrate; the thinking that must remain theirs; the evidence that will make that thinking visible; and the specific limitation the technology is meant to address.",
    },
    positioning: {
      researchEyebrow: "Research approach",
      researchTitle: "Learning design before technology",
      researchIntro: "My research follows a consistent logic: identify the educational problem, design the learning process, select technology only where it adds value, and evaluate what transfers into practice.",
      aiTitle: "AI as a thinking partner",
      aiText: "Students should reason first. AI can then question, challenge, and widen the discussion, but the learner must verify, revise, and defend the final judgement.",
      aiSequence: ["Reason", "Question", "Challenge", "Verify", "Revise", "Defend"],
      vriloEyebrow: "Practical design pathway",
      vriloTitle: "The VRILO pathway",
      vriloIntro: "VRILO is a practical seven-stage pathway for designing and implementing VR learning. It is presented as a developing design guide, not as a universally validated framework.",
      vriloStages: ["Define the educational problem", "Specify intended learning outcomes", "Decide whether VR is appropriate", "Design the learning experience", "Prepare implementation and support", "Align assessment, access, and fairness", "Evaluate, refine, and plan for sustainability"],
      teachingEyebrow: "Learning architecture",
      teachingTitle: "Preparing students for authentic complexity",
      teachingIntro: "My teaching connects university preparation with progressively more authentic practice, while keeping educator guidance and clinical judgement visible throughout.",
      teachingSteps: ["University preparation", "Safe rehearsal", "Reasoning practice", "Simulation", "Clinical placement", "Authentic complexity", "Professional judgement"],
      teachingClosing: "Clinical educators are essential partners in this progression: they connect curriculum intentions with the realities, feedback, and responsibility of practice.",
    },
    media: {
      eyebrow: "Media desk · In development",
      title: "Watch, listen, and explore the work in progress",
      intro: "This will become a curated collection of teaching demonstrations, project walkthroughs, presentations, and conversations about physiotherapy education, AI, virtual reality, and clinical reasoning.",
      status: "Collection in preparation",
      formatsEyebrow: "Planned formats",
      formatsTitle: "More than one way into an idea",
      formatsIntro: "Each format will be chosen for what it helps an audience see, hear, or understand, rather than simply repackaging the same material.",
      formats: [
        ["Video", "Teaching demonstrations, project walkthroughs, and short explanations of educational design decisions.", "Preparing the first release"],
        ["Presentations", "Selected conference slides, invited talks, and narrated presentations with enough context to stand on their own.", "Curating materials"],
        ["Podcasts and conversations", "Focused discussions with educators, clinicians, researchers, and students about ideas worth examining together.", "Format in development"],
        ["Visual stories", "Photographs, diagrams, prototypes, and classroom snapshots that make the design process visible.", "Building the collection"],
      ],
      principlesEyebrow: "Publishing standard",
      principlesTitle: "Useful before impressive",
      principlesIntro: "Media will be published only when it adds something that text alone cannot show clearly.",
      principles: [
        ["Context included", "Every item will explain the educational problem, audience, and purpose behind it."],
        ["Accessible by design", "Videos and audio will include captions or transcripts; presentation files will include readable supporting notes."],
        ["Evidence made visible", "Claims, limitations, and links to relevant research will travel with the media."],
        ["Consent and rights respected", "Student work, photographs, recordings, and slides will appear only when permissions and reuse rights are clear."],
      ],
      firstEyebrow: "First collection",
      firstTitle: "Themes currently being scoped",
      firstItems: ["Virtual reality acupuncture learning", "Practical AI literacy for health professionals", "Designing AI-supported clinical reasoning", "Behind the design of technology-enhanced teaching"],
      note: "There are no empty recordings here yet. New items will appear when the media, description, accessibility materials, and permissions are ready together.",
      instagramEyebrow: "From practice",
      instagramTitle: "Professional moments on Instagram",
      instagramIntro: "A selected record of teaching, presentations, academic visits, and practical learning shared publicly on Instagram.",
      instagramAction: "View on Instagram",
      instagramProfileAction: "Follow @yutakwing002",
      instagramItems: [
        ["VR teaching at Saint Francis University", "A short university feature on using virtual reality for healthcare training, physiotherapy simulation, and clinical decision-making.", "Teaching feature", "16 Jul 2026", "https://www.instagram.com/sfu.physio/reel/Da2cR3eNiNT/"],
        ["14th Pan Pacific Conference on Rehabilitation", "A presentation from the rehabilitation conference held on 8–9 November 2025.", "Conference presentation", "14 Jul 2026", "https://www.instagram.com/yutakwing002/p/DaxgoRDlIme/"],
        ["Western Sydney University visit", "A record of an academic visit and farewell dinner with colleagues at Western Sydney University.", "Academic visit", "15 Jul 2026", "https://www.instagram.com/yutakwing002/p/DazrNGFJXrX/"],
        ["Learning anatomy in the HKU wet laboratory", "A practical anatomy-learning experience reflecting the value of seeing structure beyond diagrams and screens.", "Practical learning", "14 Jul 2026", "https://www.instagram.com/yutakwing002/p/DaxQ5PMpRLK/"],
        ["World Physiotherapy Congress 2025", "A conference reflection shared with colleagues Dr Choi and Professor Leung.", "Conference", "14 Jul 2026", "https://www.instagram.com/yutakwing002/p/DaxQNCQJ64T/"],
        ["Behind the scenes of a pin-test exercise", "A brief look at the preparation involved in building a practical assessment activity.", "Assessment design", "14 Jul 2026", "https://www.instagram.com/yutakwing002/p/DaxPcbZJ5Gy/"],
      ],
    },
    collaborate: {
      eyebrow: "Work together",
      title: "Let us build something useful",
      intro: "I enjoy collaborating with educators, clinicians, researchers, designers, and students who are exploring meaningful improvements in health professions education.",
      interestsTitle: "I am especially interested in",
      interests: ["AI and clinical reasoning", "Virtual reality in health professions education", "Simulation and clinical education", "Educational research"],
      invitation: "A good first message tells me what educational problem you are working on, who the learners are, and what you hope to understand or improve.",
      ctaTitle: "Have a project in one of these areas?",
      actions: ["Discuss a research project", "Invite me to speak", "Explore a teaching collaboration"],
      details: "Contact details",
      profiles: "Academic profiles",
    },
    projectsData: [
      {
        id: "vr-acupuncture",
        number: "01",
        title: "Virtual Reality Acupuncture",
        strapline: "Turning a spatial and safety-sensitive skill into a structured cycle of preparation, practice, and assessment.",
        image: "virtual-anatomy.webp",
        imageAlt: "Illustrative virtual anatomy learning environment used to represent immersive acupuncture education.",
        imageNote: "Illustrative project image",
        problem: "Students need repeated opportunities to connect anatomy, point location, safety, and procedural reasoning, but access to guided practice is limited by time, place, and supervision.",
        design: "A curriculum-aligned VR application with training, practice, and assessment modes, supported by preparation and debriefing rather than treated as a stand-alone simulation.",
        learning: "Spatial orientation, anatomical relationships, procedural sequence, safety decisions, and explanation of technique.",
        role: "Educational designer and lecturer supporting development and curriculum integration.",
        status: "Current project: development and curriculum integration.",
        next: "Which parts of the learning experience are improved by immersion, and which still require direct teaching and physical practice?",
      },
      {
        id: "ai-literacy",
        number: "02",
        title: "AI Literacy for Health Professionals",
        strapline: "Helping learners verify, disclose, question, and remain accountable for AI-supported work.",
        image: "lecturer-ai-literacy.webp",
        imageAlt: "Health professions educators discussing practical AI literacy in a collaborative workshop illustration.",
        imageNote: "Editorial illustration",
        problem: "Using a chatbot is not the same as understanding hallucination, bias, privacy, verification, or professional accountability.",
        design: "A developing sequence of curriculum prompts, reflective writing, and a short interactive knowledge check that makes responsible-use decisions concrete.",
        learning: "Source verification, privacy judgement, bias awareness, disclosure, appropriate task selection, and responsibility for final decisions.",
        role: "Lecturer and educational designer developing practical AI-literacy activities.",
        status: "Active teaching resource and curriculum-development theme.",
        next: "How should practical AI literacy be assessed without reducing it to tool familiarity or policy recall?",
      },
      {
        id: "reasoning-chatbot",
        number: "03",
        title: "Clinical Reasoning Chatbot",
        strapline: "Designing AI to ask better questions before it offers answers.",
        image: "ai-thinking-partner.webp",
        imageAlt: "A physiotherapy educator and student using AI as a structured support for clinical reasoning.",
        imageNote: "Editorial illustration",
        problem: "AI can produce plausible clinical answers before students have identified red flags, compared hypotheses, or justified a plan.",
        design: "A pilot chatbot that prioritises safety screening, staged questioning, explanation, and reflection before suggestions are revealed.",
        learning: "Red-flag recognition, hypothesis generation, evidence use, prioritisation, explanation, and critical review of AI output.",
        role: "Researcher and educational designer leading the pilot concept and learning design.",
        status: "Pilot study in development; no claims of effectiveness are made yet.",
        next: "Can structured AI dialogue improve the visibility and quality of student reasoning without creating over-reliance?",
      },
      {
        id: "physiology-vr",
        number: "04",
        title: "Teaching Human Physiology with VR",
        strapline: "Using immersion to connect structure, function, movement, and clinical meaning.",
        image: "vr-platform-comparison.webp",
        imageAlt: "Virtual reality headsets and immersive health-science learning environments.",
        imageNote: "Editorial illustration",
        problem: "Dynamic physiological relationships can remain abstract when students encounter them only as diagrams, slides, or isolated facts.",
        design: "Short immersive encounters embedded within a wider lesson: preparation, guided observation, case application, peer explanation, and debriefing.",
        learning: "Three-dimensional relationships, structure-function connections, observation, explanation, and transfer to clinical cases.",
        role: "Lecturer designing and refining the surrounding learning sequence.",
        status: "Teaching approach under iterative development.",
        next: "What is the smallest useful dose of immersion, and how should the surrounding lesson be designed to make it count?",
      },
      {
        id: "simulation-role-rotation",
        number: "05",
        title: "Simulation in Health Professions Education",
        strapline: "Exploring how different simulation roles may direct attention towards different aspects of learning.",
        image: "role-rotation-simulation-v2.webp",
        imageAlt: "Physiotherapy students rotating between clinician, peer patient, observer, and peer debriefer roles in a simulation laboratory.",
        imageNote: "Editorial illustration",
        problem: "Simulation learning is often discussed mainly in relation to the student performing as the clinician, while less is known about what students may learn as peer patients, observers, or peer debriefers.",
        design: "A structured role-rotation model involving Learner, Peer Patient, Observer, and Peer Debriefer roles, supported by role preparation, focused observation, guided reflection, and educator oversight for clinical accuracy and psychological safety.",
        learning: "Early student accounts suggest different emphases across roles: clinical integration, patient-centred awareness, analytical distance, and feedback dialogue. These are perceived learning possibilities rather than confirmed effects.",
        role: "Researcher and lecturer contributing to the role-rotation design and ongoing analysis.",
        status: "Ongoing analysis and manuscript development; effects on clinical competence and readiness have not been established.",
        next: "Do role-specific learning experiences transfer to later simulation or clinical practice, and how can this be measured beyond self-report?",
      },
    ],
  },
};

const traditional = {
  nav: { home: "主頁", about: "關於", research: "研究", teaching: "教學", writing: "寫作", media: "媒體", resources: "資源", collaborate: "與我合作" },
  home: {
    eyebrow: "公開學術實驗室", name: "庾德榮", role: "物理治療高級講師", disciplines: "物理治療師 · 教育工作者 · 研究人員 · 學習設計者",
    title: "透過人工智能、虛擬實境與模擬教學，設計更有效的臨床推理學習方式。",
    identity: "我探索新興科技如何支援健康專業教育中的批判思考、體驗式學習與實踐準備，同時不取代臨床照護核心的人類判斷。",
    lede: "我的工作從教育問題出發，再探討科技能否讓思考更可見、練習更有意義，或回饋更具價值。",
    actions: ["探索學術實驗室", "查看精選工作", "關於我", "與我合作"],
    credibilityEyebrow: "立足實務",
    credibility: [["2026", "教學卓越獎", "繼 2025 年獲提名後，於學院層面獲得嘉許。"], ["人工智能 · 虛擬實境 · 模擬", "教育重點", "圍繞臨床推理與實踐準備而設計。"], ["設計為本研究", "研究取向", "反覆發展、評估與誠實改進。"], ["香港 · 南非", "學術視角", "連結不同脈絡下的物理治療教育。"]],
    nowEyebrow: "目前工作", nowTitle: "我正在探索、建立、測試與學習的事情", nowIntro: "目前影響我教學與研究的問題。",
    now: [["探索", "讓推理變得可見", "人工智能如何呈現學生思考，而不成為臨床捷徑。", "研究", "research", "ai-literacy"], ["建立", "善於提問的聊天機械人", "以安全篩查與學習者解釋為核心的臨床推理工具。", "發展", "research", "reasoning-chatbot"], ["測試", "沉浸式練習", "虛擬實境如何支援針灸、解剖與動作科學。", "試點", "research", "vr-acupuncture"], ["學習", "可持續實施", "有效採用科技除了購買平台之外還需要甚麼。", "寫作", "writing", ""]],
    projectsEyebrow: "精選工作", projectsTitle: "學術實驗室的實踐證據", projectsIntro: "精選項目呈現教育問題、設計回應、我的角色及目前狀態，並避免誇大現有證據。",
    projectLabels: { problem: "問題", approach: "方法", role: "我的角色", status: "狀態", action: "探索項目" },
    experienceEyebrow: "親身體驗", experienceTitle: "不只閱讀，更能從實踐中學習", experienceIntro: "透過短篇互動活動，探索臨床推理、人工智能、虛擬實境與模擬教學。",
    experiences: [["臨床準備實驗室", "以俯視角互動學習體驗，探索健康專業教育中的人工智能、虛擬實境與模擬教學。", "clinical-readiness-lab.html", "進入實驗室", "互動實驗室"], ["推理跑者", "辨認紅旗、核實證據，並選擇較安全的臨床回應，避開不安全的人工智能說法。", "reasoning-runner.html", "開始推理跑者", "互動挑戰"], ["人工智能素養檢查", "檢視核實、私隱、偏見、披露與專業責任的反思式知識檢查。", "ai-literacy-check.html", "開始檢查", "15 題"]],
    impactEyebrow: "精選里程碑", impactTitle: "以工作為本的認可", impactIntro: "簡要記錄本網站已載述的教學、學術與教育發展工作。",
    impact: [["2026 年教學卓越獎", "於學院層面肯定以學生為本的教學、課程發展及具目的的教育創新。", "writing", "two-years-in-hong-kong-reflecting-on-teaching-innovation-and-receiving-a-teaching-excellence-award"], ["已發表的虛擬實境教育研究", "經同行評審的研究，探討教育工作者對健康專業教育沉浸式虛擬實境的觀點。", "research", "publications"], ["虛擬實境針灸發展", "配合課程的學習應用程式，設有訓練、練習與評估模式。", "research", "vr-acupuncture"], ["模擬角色輪換研究", "持續分析學生擔任臨床學習者、同儕病人、觀察者與同儕反思引導者時可能學到甚麼。", "research", "simulation-role-rotation"]],
    snapshotsEyebrow: "走進課堂", snapshotsTitle: "教學快照", snapshotsIntro: "教育理念如何成為學生實際可以完成的學習活動。",
    writingEyebrow: "設計背後", writingTitle: "最新文章", writingIntro: "教育創新背後的決定、張力、限制與偶爾失敗的近期反思。", writingAction: "閱讀文章", writingAll: "探索所有文章",
    flagshipEyebrow: "重點工作",
    flagshipTitle: "推動我工作的三個問題",
    flagshipIntro: "每項工作都從學習問題出發。只有當科技能改善推理、練習、回饋及臨床責任準備時，我才會採用它。",
    flagshipLabels: { problem: "教育問題", approach: "教學方法", pathway: "學習次序", status: "證據狀態" },
    flagships: [
      ["人工智能輔助臨床推理", "如何讓學習者在流暢的人工智能答案掩蓋不確定性之前，解釋、質疑及修正自己的推理？", "我把人工智能用作蘇格拉底式思考伙伴：學生先自行推理，再提問、核實、修正及論證自己的判斷。", "推理 → 提問 → 挑戰 → 修正 → 論證", "試點", "research", "reasoning-chatbot", "探索人工智能與推理"],
      ["具目的的虛擬實境沉浸學習", "如何讓學習者安全地練習空間性、具身性或難以接觸的經驗，而不把新鮮感誤當成學習？", "我把沉浸體驗與明確學習成果、學習準備、引導練習、回饋及反思整合。", "看見 → 探索 → 練習 → 重複", "發展中", "research", "vr-acupuncture", "探索虛擬實境工作"],
      ["模擬與實踐準備", "學生如何在面對臨床實習的複雜情境前，預演決策及專業責任？", "我圍繞真實實務決策，設計結構化情境、角色輪換、觀察、回饋及反思。", "預演 → 決定 → 接收回饋 → 調整", "持續研究", "research", "simulation-role-rotation", "探索模擬研究"],
    ],
    connectionEyebrow: "工作如何連結",
    connectionTitle: "從學習準備走向臨床責任",
    connectionIntro: "這些並非彼此分割的科技，而是一條通往更安全、更負責任專業判斷的學習路徑。",
    connectionSteps: [["虛擬實境", "看見、體驗與練習"], ["人工智能", "推理、提問與挑戰"], ["模擬", "預演、接收回饋與調整"], ["臨床實習", "轉移學習並承擔責任"]],
    connectionClosing: "科技協助準備；臨床經驗讓學習變得真實。",
    collaborateEyebrow: "合作", collaborateTitle: "與我合作", collaborateIntro: "我歡迎在健康專業教育的研究、教學創新、課程發展與教育科技方面進行合作。",
    collaborationThemes: ["人工智能與臨床推理", "虛擬實境課程整合", "模擬與臨床教育", "教育研究"],
    collaborationActions: ["討論研究項目", "邀請我演講", "探索教學合作"],
    invitationTitle: "這是一個實驗室，而不是檔案館。", invitationText: "項目會演變，問題會改變，有用資源亦會在準備好時分享。目標是讓教育設計的過程變得可見。",
  },
  story: {
    eyebrow: "我的歷程", title: "從動作走向意義", intro: "我的工作從理解人如何活動，逐步走向思考未來物理治療師如何學會思考、判斷與照顧。",
    chapters: [["為何選擇物理治療", "物理治療把科學理解與實際的人類判斷連結起來。動作可以量度，但良好照護仍依賴聆聽、推理、調整，以及看見疾病以外的整個人。"], ["為何走進教育", "教學讓臨床推理中隱藏的工作變得清楚。學生需要的不只是更多資訊，而是解釋決定、檢驗假設、安全犯錯，以及把理論連接眼前個案的機會。"], ["為何研究虛擬實境", "虛擬實境可讓困難、空間性強或較少遇到的經驗更容易接觸。我關注的不是沉浸感本身，而是精心設計的經驗能否協助學生看見、練習及理解其他方法難以呈現的內容。"], ["為何研究人工智能", "人工智能可擴展回饋及產生可能性，也可用流暢答案掩蓋薄弱推理。我希望設計讓學生先思考、再使用人工智能，並對最終判斷負責。"]],
    philosophyTitle: "我希望解決的問題", philosophy: "我們如何設計能呈現臨床推理、保留重要人類判斷，並只在具真正教育價值時使用科技的學習經驗？",
    principles: [["從學習者開始", "先界定能力、誤解或障礙，再選擇工具。"], ["讓思考可見", "要求學生解釋、比較、辯護及修正決定。"], ["為轉移而設計", "把課堂活動連接專業實踐中的不確定性與責任。"], ["誠實評估", "把阻力、失敗與意外後果視為下一輪設計的證據。"]],
  },
  projects: { eyebrow: "標誌性工作", title: "精選項目", intro: "這些項目圍繞同一目標，把物理治療、人工智能、虛擬實境、模擬與教育設計連結起來：改善學生發展及展示臨床推理的方式。", knownFor: "我希望以設計具證據基礎的人工智能及虛擬實境物理治療教育方法見稱，同時不讓科技取代學生必須學會完成的思考。", labels: { problem: "問題", design: "設計回應", learning: "學習者練習甚麼", status: "目前狀態", next: "下一個問題" } },
  ideas: { eyebrow: "開放筆記本", title: "發展中的想法", intro: "仍在發展的問題、實驗與影響來源。學術思考在未完成的邊緣仍然可見時，往往更有用。", workingTitle: "我正在做甚麼", workingIntro: "2026 年 7 月更新", questionsTitle: "工作台上的問題", readingEyebrow: "閱讀", readingCardLabel: "閱讀主題", readingTitle: "目前閱讀主題", visionTitle: "2030 願景", vision: "到 2030 年，最有用的教育科技未必最具視覺效果，而是能讓推理更可見、練習更易接觸、回饋更及時，並讓專業責任更難被迴避的工具。", working: ["人工智能輔助安全篩查與臨床推理", "虛擬實境輔助針灸學習與評估", "在科技增強任務中呈現學習者推理", "動作分析與科技輔助復康"], questions: ["人工智能回饋何時深化推理，何時暗中取代推理？", "物理治療課程中哪些部分應刻意保持不用人工智能？", "多少沉浸體驗具教育價值，何時認知負荷會成為障礙？", "學生如何呈現技術上正確答案背後的推理？"], reading: [["情境學習", "參與、脈絡及專業社群如何塑造學習。"], ["設計為本研究", "反覆設計如何同時產生實務改善與可轉移知識。"], ["醫學教育中的人工智能", "現有證據對學習、評估、管治與專業責任的啟示。"]] },
  resources: { eyebrow: "實用內容", title: "教育工作者資源", intro: "實用工具及設計提示會在準備好時分享。發展中材料會清楚標示，不會當作完成品。", available: "現已提供", developing: "發展中", items: [["推理跑者", "以遊戲方式練習證據核實、紅旗辨認及回應不安全人工智能說法。", "reasoning-runner.html", "開始遊戲"], ["臨床準備實驗室", "透過三個互動學習站探索人工智能、虛擬實境及模擬教學。", "clinical-readiness-lab.html", "進入實驗室"], ["肘關節量角器挑戰", "對準量角器的中心軸、固定臂與移動臂，以解剖標誌練習肘關節伸展測量。", "elbow-goniometry", "開始挑戰"], ["踝關節量角器挑戰", "運用外踝、腓骨頭及第五蹠骨等解剖標誌，練習量度踝關節背屈。", "ankle-goniometry", "開始挑戰"], ["肩關節量角器挑戰", "在站立位運用肱骨頭外側、腋中線及肱骨外上髁，練習量度肩關節屈曲與伸展。", "shoulder-goniometry", "開始挑戰"], ["肩關節旋轉量角器挑戰", "從側面觀察仰臥位，運用尺骨鷹嘴、垂直參考線及尺骨莖突，練習量度肩關節內旋與外旋。", "shoulder-rotation-goniometry", "開始挑戰"], ["人工智能素養檢查", "關於核實、私隱、偏見及負責任使用的 15 題反思活動。", "ai-literacy-check.html", "開啟活動"], ["學術筆記庫", "連接教育、科技、物理治療與研究的筆記。", "notes.html", "瀏覽筆記"], ["寫作檔案", "按物理治療、人工智能與專業反思整理的文章。", "writing.html", "閱讀文章"]], developingItems: [["臨床推理活動規劃工具", "用以配合個案、學習者決定、證據、回饋與評估的提示。"], ["虛擬實境實施清單", "檢視課程配合、無障礙使用、學習者準備、技術支援及評估。"], ["負責任人工智能任務範本", "界定獲准人工智能用途，以及學生仍須自行提供的證據。"]], promptTitle: "今天可以使用的設計提示", prompt: "加入科技前，先寫下：學生必須展示的能力、必須由學生完成的思考、能呈現該思考的證據，以及科技要處理的具體限制。" },
  positioning: {
    researchEyebrow: "研究方法", researchTitle: "學習設計先於科技", researchIntro: "我的研究採用一致的邏輯：先找出教育問題，設計學習過程，只在科技能增值時才採用，並評估學習能否轉移至實務。",
    aiTitle: "人工智能作為思考伙伴", aiText: "學生應先自行推理，人工智能再用作提問、挑戰及擴闊討論；最終判斷仍須由學習者核實、修正及論證。", aiSequence: ["推理", "提問", "挑戰", "核實", "修正", "論證"],
    vriloEyebrow: "實用設計路徑", vriloTitle: "VRILO 路徑", vriloIntro: "VRILO 是設計及實施虛擬實境學習的七階段實用路徑。它是一項持續發展的設計指南，並非已獲普遍驗證的框架。", vriloStages: ["界定教育問題", "訂立預期學習成果", "判斷虛擬實境是否合適", "設計學習體驗", "準備實施與支援", "配合評估、可及性與公平", "評估、修正及規劃可持續性"],
    teachingEyebrow: "學習架構", teachingTitle: "為真實的複雜情境作準備", teachingIntro: "我的教學把大學準備與逐步增加真實性的實踐連結起來，並在整個過程中保留教育工作者的指導及臨床判斷。", teachingSteps: ["大學準備", "安全預演", "推理練習", "模擬", "臨床實習", "真實複雜情境", "專業判斷"], teachingClosing: "臨床教育工作者是這個進程的重要伙伴：他們把課程目標與實務中的現實、回饋及責任連結起來。",
  },
  media: {
    eyebrow: "媒體工作台 · 發展中",
    title: "觀看、聆聽並探索發展中的工作",
    intro: "這裏將成為一個精選媒體庫，收錄教學示範、項目導覽、簡報，以及關於物理治療教育、人工智能、虛擬實境與臨床推理的對話。",
    status: "內容整理中",
    formatsEyebrow: "規劃中的形式",
    formatsTitle: "以不同方式進入同一個想法",
    formatsIntro: "每種形式都會按它能協助觀眾看見、聽見或理解甚麼而選擇，而不是把相同內容重新包裝。",
    formats: [
      ["影片", "教學示範、項目導覽，以及教育設計決定的短篇解說。", "正在準備首項內容"],
      ["簡報", "精選會議投影片、獲邀演講及附旁白的簡報，並提供足夠背景以便獨立理解。", "正在整理材料"],
      ["Podcast 與對話", "與教育工作者、臨床人員、研究人員及學生，聚焦討論值得共同探究的想法。", "形式發展中"],
      ["視覺故事", "以相片、圖表、原型與課堂快照，呈現教育設計的過程。", "正在建立內容庫"],
    ],
    principlesEyebrow: "發布標準",
    principlesTitle: "實用先於吸引眼球",
    principlesIntro: "只有當媒體能清楚呈現文字本身難以表達的內容時，才會正式發布。",
    principles: [
      ["交代背景", "每項內容都會說明其教育問題、對象及設計目的。"],
      ["以無障礙為設計原則", "影片與音訊會附字幕或文字稿；簡報檔案會提供清晰易讀的補充說明。"],
      ["呈現證據", "相關主張、限制及研究連結會與媒體一併提供。"],
      ["尊重同意與版權", "學生作品、相片、錄音及投影片只會在權限與再用權利清楚時發布。"],
    ],
    firstEyebrow: "首批內容",
    firstTitle: "目前正在規劃的主題",
    firstItems: ["虛擬實境針灸學習", "健康專業實用人工智能素養", "設計人工智能輔助臨床推理", "科技增強教學的設計背後"],
    note: "目前不會展示空白的錄音或影片。只有當媒體、說明、無障礙材料及相關權限均準備妥當時，新內容才會在此出現。",
    instagramEyebrow: "來自實踐",
    instagramTitle: "Instagram 上的專業片段",
    instagramIntro: "精選公開分享的教學、簡報、學術探訪與實務學習紀錄。",
    instagramAction: "在 Instagram 查看",
    instagramProfileAction: "追蹤 @yutakwing002",
    instagramItems: [
      ["聖方濟各大學的虛擬實境教學", "大學短片介紹虛擬實境如何應用於醫療培訓、物理治療模擬及臨床決策學習。", "教學短片", "2026 年 7 月 16 日", "https://www.instagram.com/sfu.physio/reel/Da2cR3eNiNT/"],
      ["第十四屆泛太平洋復康會議", "記錄於 2025 年 11 月 8 至 9 日舉行的復康會議簡報。", "會議簡報", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxgoRDlIme/"],
      ["西悉尼大學學術探訪", "與西悉尼大學同事交流及出席歡送晚宴的學術探訪紀錄。", "學術探訪", "2026 年 7 月 15 日", "https://www.instagram.com/yutakwing002/p/DazrNGFJXrX/"],
      ["在香港大學濕實驗室學習解剖", "一次實務解剖學習經驗，反思在圖表與螢幕以外直接觀察結構的價值。", "實務學習", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxQ5PMpRLK/"],
      ["2025 年世界物理治療大會", "與 Choi 博士及 Leung 教授一同參與會議的反思紀錄。", "會議", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxQNCQJ64T/"],
      ["設計針刺測試練習的幕後工作", "簡短呈現準備實務評估活動所涉及的工作。", "評估設計", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxPcbZJ5Gy/"],
    ],
  },
  collaborate: { eyebrow: "共同工作", title: "一起建立真正有用的東西", intro: "我樂於與探索健康專業教育改善的教育工作者、臨床人員、研究人員、設計師及學生合作。", interestsTitle: "我特別有興趣合作的範疇", interests: ["人工智能與臨床推理", "健康專業教育中的虛擬實境", "模擬與臨床教育", "教育研究"], invitation: "一封良好的初次訊息可以告訴我：你正在處理甚麼教育問題、學習者是誰，以及你希望理解或改善甚麼。", ctaTitle: "你是否正在進行這些範疇的項目？", actions: ["討論研究項目", "邀請我演講", "探索教學合作"], details: "聯絡資料", profiles: "學術平台" },
};

const toSimplified = (value) => {
  const phrases = [
    ["虛擬實境", "虚拟现实"], ["物理治療", "物理治疗"], ["健康專業", "健康专业"],
    ["臨床推理", "临床推理"], ["機械人", "机器人"], ["人工智能", "人工智能"],
    ["回饋", "反馈"], ["復康", "康复"], ["管治", "治理"], ["個案", "案例"],
    ["資訊", "信息"], ["範疇", "领域"], ["甚麼", "什么"], ["現行", "当前"],
    ["課堂", "课堂"], ["學習者", "学习者"], ["同儕", "同伴"], ["無障礙", "无障碍"],
    ["反覆", "反复"], ["教學卓越獎", "教学卓越奖"], ["演講", "演讲"],
    ["支援", "支持"], ["應用程式", "应用程序"], ["私隱", "隐私"], ["現時", "当前"],
    ["量度", "测量"],
  ];
  const characters = {
    "與":"与","體":"体","學":"学","習":"习","實":"实","驗":"验","開":"开","發":"发","項":"项","機":"机",
    "臨":"临","專":"专","業":"业","課":"课","評":"评","設":"设","計":"计","這":"这","讓":"让","還":"还",
    "為":"为","應":"应","務":"务","現":"现","後":"后","結":"结","構":"构","準":"准","備":"备","練":"练",
    "強":"强","視":"视","轉":"转","間":"间","場":"场","導":"导","連":"连","並":"并","訓":"训","說":"说",
    "協":"协","檢":"检","識":"识","決":"决","變":"变","負":"负","責":"责","隱":"隐","來":"来","見":"见",
    "選":"选","終":"终","狀":"状","態":"态","稱":"称","時":"时","須":"须","輸":"输","動":"动","圖":"图",
    "關":"关","維":"维","觀":"观","將":"将","錯":"错","誤":"误","護":"护","聽":"听","調":"调","見":"见",
    "經":"经","驗":"验","較":"较","難":"难","內":"内","產":"产","擴":"扩","暢":"畅","蓋":"盖","斷":"断",
    "優":"优","階":"阶","顯":"显","議":"议","證":"证","據":"据","紅":"红","認":"认","對":"对","話":"话",
    "質":"质","邊":"边","週":"周","啟":"启","覺":"觉","覓":"觅","讀":"读","書":"书","寫":"写","庫":"库",
    "筆":"笔","記":"记","聯":"联","絡":"络","資":"资","源":"源","瀏":"浏","覽":"览","檔":"档","案":"案",
    "從":"从","進":"进","來":"来","師":"师","療":"疗","科":"科","義":"义","難":"难","觸":"触","獲":"获",
    "確":"确","稱":"称","據":"据","礎":"础","邏":"逻","輯":"辑","極":"极","續":"续","買":"买","東":"东",
    "儀":"仪","器":"器","對":"对","興":"兴","願":"愿","難":"难","離":"离","態":"态","還":"还","廣":"广",
    "類":"类","處":"处","隨":"随","機":"机","編":"编","輯":"辑","插":"插","繪":"绘","示":"示","標":"标",
    "樂":"乐","員":"员","別":"别","輔":"辅","訊":"讯","問":"问","誰":"谁","術":"术","閱":"阅","參":"参",
    "脈":"脉","醫":"医","響":"响","緣":"缘","篩":"筛","針":"针","價":"价","會":"会","礙":"碍","題":"题",
    "運":"运","個":"个","徑":"径","測":"测","踐":"践","釋":"释","購":"购","環":"环","養":"养","係":"系",
    "頭":"头","蹠":"跖","臥":"卧","側":"侧","線":"线",
    "審":"审","擇":"择","館":"馆","過":"过","圍":"围","繞":"绕","誌":"志","簡":"简","憶":"忆","劃":"划",
    "規":"规","單":"单","該":"该","當":"当","於":"于","歷":"历","顧":"顾","際":"际","賴":"赖","論":"论",
    "們":"们","麼":"么","適":"适","達":"达","辦":"办","帶":"带","傳":"传","統":"统","層":"层","嚴":"严",
    "著":"着","點":"点","據":"据","擔":"担","發":"发","啟":"启","實":"实","礙":"碍","壓":"压","灣":"湾",
    "範":"范","訴":"诉","試":"试","誠":"诚","輪":"轮","辯":"辩","迴":"回","擬":"拟",
    "換":"换","採":"采","討":"讨","監":"监","敘":"叙","報":"报","獎":"奖",
    "繼":"继","許":"许","誇":"夸","親":"亲","錄":"录","載":"载","創":"创",
    "張":"张","爾":"尔","講":"讲","領":"领","歡":"欢","戰":"战","請":"请",
    "網":"网","頁":"页","華":"华","聲":"声","響":"响","數":"数","達":"达","節":"节","軸":"轴",
    "敗":"败","鷹":"鹰","莖":"茎",
  };
  let converted = String(value);
  for (const [from, to] of phrases) converted = converted.replaceAll(from, to);
  return [...converted].map((character) => characters[character] || character).join("");
};

traditional.resources.items.splice(6, 0, [
  "髖關節量角器挑戰",
  "運用股骨大轉子、骨盆外側中線及朝向股骨外上髁的股骨外側中線，練習量度髖關節屈曲與伸展。",
  "hip-goniometry",
  "開始挑戰",
]);
traditional.resources.items.splice(7, 0, [
  "膝關節量角器挑戰",
  "運用股骨外上髁、股骨大轉子及外踝等解剖標誌，練習量度膝關節屈曲。",
  "knee-goniometry",
  "開始挑戰",
]);
traditional.resources.items.splice(9, 0, [
  "打字速度測試",
  "運用常用英文及健康專業詞彙，進行 60 秒的打字速度與準確率測試。",
  "typing-test",
  "開始測試",
]);
traditional.resources.items.splice(2, 0, [
  "量角器技能實驗室",
  "六項互動小型 OSPE 活動，練習上肢及下肢的解剖標誌辨認與量角器放置。",
  "goniometry",
  "進入實驗室",
]);

const simplified = JSON.parse(toSimplified(JSON.stringify(traditional)));
simplified.nav = { home: "主页", about: "关于", research: "研究", teaching: "教学", writing: "写作", media: "媒体", resources: "资源", collaborate: "与我合作" };
simplified.home.name = "庾德荣";
simplified.home.role = "物理治疗高级讲师";
simplified.home.disciplines = "物理治疗师 · 教育工作者 · 研究人员 · 学习设计者";
simplified.home.title = "通过人工智能、虚拟现实与模拟教学，设计更有效的临床推理学习方式。";
simplified.home.identity = "我探索新兴技术如何支持健康专业教育中的批判思考、体验式学习与实践准备，同时不取代临床照护核心的人类判断。";
simplified.home.lede = "我的工作从教育问题出发，再探讨技术能否让思考更可见、练习更有意义，或反馈更具价值。";
simplified.positioning.vriloStages = [
  "界定教育问题",
  "明确预期学习成果",
  "判断虚拟现实是否合适",
  "设计学习体验",
  "准备实施与支持",
  "衔接评估、可及性与公平",
  "评估、改进并规划可持续性",
];
simplified.resources.items[0] = ["推理跑者", "以游戏方式练习证据核实、红旗辨认及回应不安全的人工智能说法。", "reasoning-runner.html", "开始游戏"];
simplified.resources.items[1] = ["临床准备实验室", "通过三个互动学习站探索人工智能、虚拟现实及模拟教学。", "clinical-readiness-lab.html", "进入实验室"];
simplified.resources.items[2] = ["量角器技能实验室", "六项互动小型 OSPE 活动，练习上肢及下肢的解剖标志辨认与量角器放置。", "goniometry", "进入实验室"];
simplified.resources.items[7] = ["髋关节量角器挑战", "运用股骨大转子、骨盆外侧中线及朝向股骨外上髁的股骨外侧中线，练习测量髋关节屈曲与伸展。", "hip-goniometry", "开始挑战"];
simplified.resources.items[8] = ["膝关节量角器挑战", "运用股骨外上髁、股骨大转子及外踝等解剖标志，练习测量膝关节屈曲。", "knee-goniometry", "开始挑战"];
simplified.resources.items[10] = ["打字速度测试", "运用常用英文及健康专业词汇，进行 60 秒的打字速度与准确率测试。", "typing-test", "开始测试"];
simplified.media = {
  eyebrow: "媒体工作台 · 开发中",
  title: "观看、聆听并探索正在进行的工作",
  intro: "这里将成为一个精选媒体库，收录教学示范、项目导览、演示文稿，以及关于物理治疗教育、人工智能、虚拟现实与临床推理的对话。",
  status: "内容整理中",
  formatsEyebrow: "规划中的形式",
  formatsTitle: "以不同方式进入同一个想法",
  formatsIntro: "每种形式都会根据它能帮助观众看见、听见或理解什么来选择，而不是把相同内容重新包装。",
  formats: [
    ["视频", "教学示范、项目导览，以及教育设计决策的短篇讲解。", "正在准备第一项内容"],
    ["演示文稿", "精选会议演示文稿、特邀报告及附旁白的演示内容，并提供足够背景，以便独立理解。", "正在整理材料"],
    ["播客与对话", "与教育工作者、临床人员、研究人员及学生，聚焦讨论值得共同探究的想法。", "形式开发中"],
    ["视觉故事", "以照片、图表、原型与课堂快照，呈现教育设计的过程。", "正在建立内容库"],
  ],
  principlesEyebrow: "发布标准",
  principlesTitle: "实用先于夺目",
  principlesIntro: "只有当媒体能清楚呈现文字本身难以表达的内容时，才会正式发布。",
  principles: [
    ["交代背景", "每项内容都会说明其教育问题、对象及设计目的。"],
    ["以无障碍为设计原则", "视频与音频会附字幕或文字稿；演示文稿文件会提供清晰易读的补充说明。"],
    ["呈现证据", "相关主张、局限及研究链接会与媒体一并提供。"],
    ["尊重同意与版权", "学生作品、照片、录音及演示文稿只会在权限与再使用权利清楚时发布。"],
  ],
  firstEyebrow: "首批内容",
  firstTitle: "目前正在规划的主题",
  firstItems: ["虚拟现实针灸学习", "健康专业实用人工智能素养", "设计人工智能辅助临床推理", "技术增强教学的设计思路"],
  note: "目前不会展示空白的录音或视频。只有当媒体、说明、无障碍材料及相关权限均准备妥当时，新内容才会在此出现。",
  instagramEyebrow: "来自实践",
  instagramTitle: "Instagram 上的专业片段",
  instagramIntro: "精选公开分享的教学、演示、学术访问与实践学习记录。",
  instagramAction: "在 Instagram 查看",
  instagramProfileAction: "关注 @yutakwing002",
  instagramItems: [
    ["圣方济各大学的虚拟现实教学", "大学短片介绍虚拟现实如何应用于医疗培训、物理治疗模拟及临床决策学习。", "教学短片", "2026 年 7 月 16 日", "https://www.instagram.com/sfu.physio/reel/Da2cR3eNiNT/"],
    ["第十四届泛太平洋康复会议", "记录于 2025 年 11 月 8 至 9 日举行的康复会议演示。", "会议演示", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxgoRDlIme/"],
    ["西悉尼大学学术访问", "与西悉尼大学同事交流及出席欢送晚宴的学术访问记录。", "学术访问", "2026 年 7 月 15 日", "https://www.instagram.com/yutakwing002/p/DazrNGFJXrX/"],
    ["在香港大学湿实验室学习解剖", "一次实践解剖学习经历，反思在图表与屏幕以外直接观察结构的价值。", "实践学习", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxQ5PMpRLK/"],
    ["2025 年世界物理治疗大会", "与 Choi 博士及 Leung 教授一同参加会议的反思记录。", "会议", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxQNCQJ64T/"],
    ["设计针刺测试练习的幕后工作", "简短呈现准备实践评估活动所涉及的工作。", "评估设计", "2026 年 7 月 14 日", "https://www.instagram.com/yutakwing002/p/DaxPcbZJ5Gy/"],
  ],
};

const traditionalProjects = [
  {
    title: "虛擬實境針灸學習", strapline: "把空間性強且重視安全的技能，轉化為準備、練習與評估的結構化循環。",
    problem: "學生需要反覆連接解剖、穴位定位、安全與程序推理，但受時間、場地及督導所限，練習機會有限。",
    design: "建立配合課程的虛擬實境應用程式，設有訓練、練習及評估模式，並加入使用前準備與使用後解說。",
    learning: "空間定位、解剖關係、程序次序、安全判斷及技術解釋。", role: "教育設計者及講師，支援項目發展與課程整合。", status: "現行項目：正在發展及整合至課程。",
    next: "沉浸式體驗改善了哪些學習部分？哪些內容仍需要直接教學與實體練習？",
  },
  {
    title: "健康專業人工智能素養", strapline: "協助學習者核實、披露、質疑，並為人工智能輔助工作負責。",
    problem: "使用聊天機械人並不等於理解幻覺、偏見、私隱、核實及專業問責。",
    design: "發展課程設計提示、反思文章及簡短互動知識檢查，讓負責任使用的決定變得具體。",
    learning: "來源核實、私隱判斷、偏見意識、披露、任務選擇及最終決定責任。", role: "講師及教育設計者，發展實用人工智能素養活動。", status: "現行教學資源及課程發展主題。",
    next: "如何評估實用人工智能素養，而不把它簡化為工具熟悉程度或政策記憶？",
  },
  {
    title: "臨床推理聊天機械人", strapline: "讓人工智能在提供答案前，先提出更好的問題。",
    problem: "人工智能可在學生辨認紅旗、比較假設或解釋計劃前，產生看似合理的臨床答案。",
    design: "發展優先處理安全篩查、分階段提問、解釋及反思的試點聊天機械人，其後才顯示建議。",
    learning: "紅旗辨認、假設建立、證據使用、優先次序、解釋及批判審視人工智能輸出。", role: "研究人員及教育設計者，帶領試點概念與學習設計。", status: "試點研究發展中；目前並未宣稱具成效。",
    next: "結構化人工智能對話能否改善學生推理的可見度與質素，同時避免依賴？",
  },
  {
    title: "運用虛擬實境教授人體生理學", strapline: "以沉浸體驗連接結構、功能、動作與臨床意義。",
    problem: "當學生只透過圖表、投影片或孤立事實學習時，動態生理關係仍可能十分抽象。",
    design: "把短時間沉浸體驗放進完整課堂流程：準備、引導觀察、個案應用、同儕解釋及解說。",
    learning: "三維關係、結構與功能連接、觀察、解釋及轉移至臨床個案。", role: "講師，設計並持續改進周邊學習流程。", status: "教學方法正在反覆發展。",
    next: "最少而有效的沉浸體驗是多少？周邊課堂應如何設計，才能讓它真正發揮作用？",
  },
  {
    title: "健康專業模擬教育", strapline: "探索不同模擬角色可能如何把注意力帶到不同的學習面向。",
    problem: "模擬學習往往主要從擔任臨床人員的學生角度討論；學生作為同儕病人、觀察者或同儕反思引導者時可能學到甚麼，現時仍缺乏充分理解。",
    design: "採用臨床學習者、同儕病人、觀察者與同儕反思引導者的結構化角色輪換，並提供角色準備、聚焦觀察、引導反思，以及教師對臨床準確性和心理安全的監督。",
    learning: "學生的初步敘述顯示，不同角色可能分別聚焦臨床整合、以病人為本的覺察、較抽離的分析視角與回饋對話。這些是學生感受到的學習可能性，並非已確認的效果。", role: "研究人員及講師，參與角色輪換設計與持續分析。", status: "分析與論文撰寫進行中；角色輪換對臨床能力與準備度的影響尚未確立。",
    next: "不同角色的學習經驗會否轉移至日後模擬或臨床實踐？我們可以如何運用自我報告以外的方法量度？",
  },
];

const simplifiedProjects = traditionalProjects.map((project) => JSON.parse(toSimplified(JSON.stringify(project))));

const localiseProjects = (source, locale) => source.map((project, index) => ({
  ...project,
  ...(locale === "zh-hant" ? traditionalProjects[index] : simplifiedProjects[index]),
  imageAlt: locale === "zh-hant"
    ? `「${traditionalProjects[index].title}」項目的示意圖。`
    : `“${simplifiedProjects[index].title}”项目的示意图。`,
  imageNote: locale === "zh-hant" ? "項目示意圖" : "项目示意图",
}));

traditional.projectsData = localiseProjects(experienceContent.en.projectsData, "zh-hant");
simplified.projectsData = localiseProjects(experienceContent.en.projectsData, "zh-hans");

experienceContent["zh-hant"] = traditional;
experienceContent["zh-hans"] = simplified;
