const note = (id, categories, group, content) => ({ id, categories, group, content });

export const notesUi = {
  en: {
    title: "Academic Notes",
    description: "Public-safe academic notes on physiotherapy education, teaching and learning, AI, VR, simulation, and clinical technology.",
    heroEyebrow: "Public academic notebook",
    heroTitle: "Notes and connections.",
    heroDescription: "Working ideas on physiotherapy education, assessment, teaching and learning, artificial intelligence, virtual reality, simulation, and clinical technology.",
    privacy: "These are edited public versions of private working notes. Names, staffing details, internal schedules, unpublished assessment operations, and identifiable institutional information have been removed.",
    graphEyebrow: "Research pathways",
    graphTitle: "Follow the ideas",
    graphDescription: "Explore four connected pathways through the notebook. Each station opens a note; multicolour stations connect more than one theme.",
    graphLabel: "Interactive research pathways through the academic notes",
    chartRoot: "Academic notes",
    openLabel: "Open",
    libraryEyebrow: "Academic notes",
    libraryTitle: "Browse the library",
    filterLabel: "Filter notes",
    filters: { all: "All", education: "Education", technology: "Technology", physiotherapy: "Physiotherapy", research: "Research" },
    back: "Return to the archive",
  },
  "zh-hant": {
    title: "學術筆記",
    description: "經整理並適合公開閱讀的學術筆記，涵蓋物理治療教育、教與學、人工智能、虛擬實境、模擬教學及臨床科技。",
    heroEyebrow: "公開學術筆記本",
    heroTitle: "筆記與連繫。",
    heroDescription: "記錄物理治療教育、評估、教與學、人工智能、虛擬實境、模擬教學及臨床科技的工作構思。",
    privacy: "這些內容由私人工作筆記整理而成，並已刪除姓名、人手安排、內部時間表、未公開的評估運作及可識別院校的資料。",
    graphEyebrow: "研究路徑",
    graphTitle: "沿路探索構思",
    graphDescription: "透過四條互相連繫的路徑探索筆記。每個站點均可開啟筆記；多色站點代表內容連接多個主題。",
    graphLabel: "學術筆記的互動研究路徑",
    chartRoot: "學術筆記",
    openLabel: "開啟",
    libraryEyebrow: "學術筆記",
    libraryTitle: "瀏覽筆記庫",
    filterLabel: "篩選筆記",
    filters: { all: "全部", education: "教育", technology: "科技", physiotherapy: "物理治療", research: "研究" },
    back: "返回文章總覽",
  },
  "zh-hans": {
    title: "学术笔记",
    description: "经整理并适合公开阅读的学术笔记，涵盖物理治疗教育、教与学、人工智能、虚拟现实、模拟教学及临床科技。",
    heroEyebrow: "公开学术笔记本",
    heroTitle: "笔记与联系。",
    heroDescription: "记录物理治疗教育、评估、教与学、人工智能、虚拟现实、模拟教学及临床科技的工作构思。",
    privacy: "这些内容由私人工作笔记整理而成，并已删除姓名、人员安排、内部时间表、未公开的评估运作及可识别院校的信息。",
    graphEyebrow: "研究路径",
    graphTitle: "沿路探索构思",
    graphDescription: "通过四条相互联系的路径探索笔记。每个站点均可打开笔记；多色站点代表内容连接多个主题。",
    graphLabel: "学术笔记的互动研究路径",
    chartRoot: "学术笔记",
    openLabel: "打开",
    libraryEyebrow: "学术笔记",
    libraryTitle: "浏览笔记库",
    filterLabel: "筛选笔记",
    filters: { all: "全部", education: "教育", technology: "科技", physiotherapy: "物理治疗", research: "研究" },
    back: "返回文章总览",
  },
};

export const notes = [
  note("osce", "education", "education", {
    en: {
      label: "OSCE",
      eyebrow: "Assessment and simulation",
      title: "Objective Structured Clinical Examination",
      body: `<p>An OSCE should assess observable clinical competence rather than reproduce a written examination in practical form.</p><h3>Core principles</h3><ul><li>Align every station with a learning outcome and a specific clinical skill or reasoning process.</li><li>Standardise examiner prompts, simulated-patient responses, equipment, timing, and room setup.</li><li>Use a sufficient sample of stations and observations to support a defensible decision.</li><li>Ensure candidate instructions, examiner guidance, patient scripts, and rubrics are congruent.</li><li>Pilot stations and train examiners and simulated patients before implementation.</li></ul><p>A strong station makes the learner's performance visible while protecting validity, reliability, authenticity, safety, and fairness.</p>`,
    },
    "zh-hant": {
      label: "OSCE",
      eyebrow: "評估與模擬",
      title: "客觀結構式臨床考試",
      body: `<p>OSCE 應評估可觀察的臨床能力，而不是把筆試轉化為實務形式。</p><h3>核心原則</h3><ul><li>每個考站均須對應學習成果及明確的臨床技能或推理過程。</li><li>統一考官提示、模擬病人回應、設備、時間及場地設定。</li><li>採用足夠數量的考站與觀察，以支持具理據的判斷。</li><li>確保考生指示、考官指南、病人劇本及評分準則互相一致。</li><li>正式推行前先試行考站，並培訓考官與模擬病人。</li></ul><p>優良的考站能清楚呈現學習者的表現，同時保障效度、信度、真實性、安全及公平。</p>`,
    },
    "zh-hans": {
      label: "OSCE",
      eyebrow: "评估与模拟",
      title: "客观结构式临床考试",
      body: `<p>OSCE 应评估可观察的临床能力，而不是把笔试转化为实践形式。</p><h3>核心原则</h3><ul><li>每个考站均须对应学习成果及明确的临床技能或推理过程。</li><li>统一考官提示、模拟患者回应、设备、时间及场地设置。</li><li>采用足够数量的考站与观察，以支持有依据的判断。</li><li>确保考生指示、考官指南、患者脚本及评分标准相互一致。</li><li>正式实施前先试行考站，并培训考官与模拟患者。</li></ul><p>良好的考站能清楚呈现学习者的表现，同时保障效度、信度、真实性、安全及公平。</p>`,
    },
  }),
  note("functional-anatomy", "education physiotherapy", "education", {
    en: {
      label: "Functional anatomy",
      eyebrow: "Curriculum",
      title: "Functional Anatomy Curriculum Development",
      body: `<p>Functional Anatomy should connect anatomical knowledge with observation and clinical application.</p><ul><li>Emphasise surface-anatomy palpation, gait, sit-to-stand, squats, heel raises, and step assessment.</li><li>Help students connect movement quality with possible impairments.</li><li>Teach consent, appropriate exposure, draping, and respectful palpation explicitly.</li><li>Use functional movement as a rapid clinical screen alongside focused tests.</li><li>Balance directly taught content with structured independent learning.</li></ul>`,
    },
    "zh-hant": {
      label: "功能解剖學",
      eyebrow: "課程",
      title: "功能解剖學課程發展",
      body: `<p>功能解剖學應把解剖知識、觀察及臨床應用連結起來。</p><ul><li>重視表面解剖觸診、步態、坐站轉移、深蹲、提踵及踏步評估。</li><li>協助學生把動作品質與可能的功能障礙連繫起來。</li><li>明確教授同意、適當暴露、遮蓋及尊重病人的觸診方式。</li><li>把功能動作與針對性測試結合，作為快速臨床篩查。</li><li>平衡直接教授的內容與有結構的自主學習。</li></ul>`,
    },
    "zh-hans": {
      label: "功能解剖学",
      eyebrow: "课程",
      title: "功能解剖学课程发展",
      body: `<p>功能解剖学应把解剖知识、观察及临床应用联系起来。</p><ul><li>重视表面解剖触诊、步态、坐站转移、深蹲、提踵及踏步评估。</li><li>帮助学生把动作质量与可能的功能障碍联系起来。</li><li>明确教授同意、适当暴露、遮盖及尊重患者的触诊方式。</li><li>把功能动作与针对性测试结合，作为快速临床筛查。</li><li>平衡直接教授的内容与有结构的自主学习。</li></ul>`,
    },
  }),
  note("movement-science", "education physiotherapy", "education", {
    en: {
      label: "Movement science",
      eyebrow: "Curriculum",
      title: "Movement Science Development",
      body: `<p>Movement-science teaching should move from visible function to biomechanical explanation and then to clinical decision-making.</p><ul><li>Distinguish osteokinematics from arthrokinematics.</li><li>Explain open- and close-packed positions and joint roll, glide, and spin.</li><li>Connect muscle synergy, stabilisation, load distribution, and movement efficiency.</li><li>Ask learners to predict restrictions, compensations, and implications for exercise prescription.</li></ul>`,
    },
    "zh-hant": {
      label: "動作科學",
      eyebrow: "課程",
      title: "動作科學課程發展",
      body: `<p>動作科學教學應從可見的功能出發，進而解釋生物力學，最後連結至臨床決策。</p><ul><li>區分骨運動學與關節運動學。</li><li>解釋關節的鬆弛位、緊密位，以及滾動、滑動與旋轉。</li><li>連結肌肉協同、穩定、負荷分配及動作效率。</li><li>要求學習者預測活動限制、代償及其對運動處方的影響。</li></ul>`,
    },
    "zh-hans": {
      label: "动作科学",
      eyebrow: "课程",
      title: "动作科学课程发展",
      body: `<p>动作科学教学应从可见的功能出发，进而解释生物力学，最后联系至临床决策。</p><ul><li>区分骨运动学与关节运动学。</li><li>解释关节的松弛位、紧密位，以及滚动、滑动与旋转。</li><li>联系肌肉协同、稳定、负荷分配及动作效率。</li><li>要求学习者预测活动限制、代偿及其对运动处方的影响。</li></ul>`,
    },
  }),
  note("amee", "education technology", "education", {
    en: {
      label: "AMEE",
      eyebrow: "Conference synthesis",
      title: "AMEE 2023 Medical Education Notes",
      body: `<p>Key themes included microlearning, learner participation, experiential education, student wellbeing, AI, and programmatic assessment.</p><ul><li>Keep microlearning focused on one objective and avoid overcrowding.</li><li>Treat learners as stakeholders in curriculum and feedback design.</li><li>Use community and experiential learning to challenge hospital-centred assumptions.</li><li>Build belonging, trust, peer support, and workload-management skills into the curriculum.</li><li>Use multiple assessment data points over time rather than relying only on one high-stakes event.</li></ul>`,
    },
    "zh-hant": {
      label: "AMEE",
      eyebrow: "會議綜合",
      title: "AMEE 2023 醫學教育筆記",
      body: `<p>主要議題包括微學習、學習者參與、體驗式教育、學生福祉、人工智能及方案化評估。</p><ul><li>微學習應聚焦單一目標，避免內容過度擁擠。</li><li>把學習者視為課程及回饋設計的持份者。</li><li>運用社區及體驗式學習，挑戰以醫院為中心的假設。</li><li>把歸屬感、信任、同儕支援及工作量管理能力納入課程。</li><li>運用一段時間內的多項評估資料，而不是只依賴一次高風險考核。</li></ul>`,
    },
    "zh-hans": {
      label: "AMEE",
      eyebrow: "会议综合",
      title: "AMEE 2023 医学教育笔记",
      body: `<p>主要议题包括微学习、学习者参与、体验式教育、学生福祉、人工智能及方案化评估。</p><ul><li>微学习应聚焦单一目标，避免内容过度拥挤。</li><li>把学习者视为课程及反馈设计的利益相关者。</li><li>运用社区及体验式学习，挑战以医院为中心的假设。</li><li>把归属感、信任、同伴支持及工作量管理能力纳入课程。</li><li>运用一段时间内的多项评估数据，而不是只依赖一次高风险考核。</li></ul>`,
    },
  }),
  note("student-engagement", "education", "education", {
    en: {
      label: "Engagement",
      eyebrow: "Teaching and learning",
      title: "Student Engagement in Health Professions Education",
      body: `<p>Engagement is influenced by lesson structure, clinical relevance, lecturer presence, feedback, and opportunities for interaction.</p><ul><li>Break long sessions into purposeful segments and changes of activity.</li><li>Use clinical cases, brief videos, interactive questions, simulation, and carefully reviewed AI-generated cases.</li><li>State the topic and intended learning clearly at the start.</li><li>Use movement, voice, appropriate humour, and responsiveness deliberately.</li><li>Address barriers such as abstract content, weak interaction, overloaded timetables, and poor attendance.</li></ul>`,
    },
    "zh-hant": {
      label: "學生參與",
      eyebrow: "教與學",
      title: "健康專業教育中的學生參與",
      body: `<p>學生參與受課堂結構、臨床相關性、教師投入、回饋及互動機會影響。</p><ul><li>把長課堂分成有明確目的的環節，並適時轉換活動。</li><li>運用臨床個案、短片、互動提問、模擬教學及經審核的人工智能生成個案。</li><li>在課堂開始時清楚說明主題與預期學習。</li><li>有意識地運用走動、聲線、合宜幽默及即時回應。</li><li>處理內容抽象、互動不足、時間表過密及出席率低等障礙。</li></ul>`,
    },
    "zh-hans": {
      label: "学生参与",
      eyebrow: "教与学",
      title: "健康专业教育中的学生参与",
      body: `<p>学生参与受课堂结构、临床相关性、教师投入、反馈及互动机会影响。</p><ul><li>把长课堂分成有明确目的的环节，并适时转换活动。</li><li>运用临床案例、短片、互动提问、模拟教学及经审核的人工智能生成案例。</li><li>在课堂开始时清楚说明主题与预期学习。</li><li>有意识地运用走动、声线、适当幽默及即时回应。</li><li>处理内容抽象、互动不足、时间表过密及出席率低等障碍。</li></ul>`,
    },
  }),
  note("teaching-technology", "education technology", "education", {
    en: {
      label: "Learning technology",
      eyebrow: "Learning design",
      title: "Teaching and Learning with Technology",
      body: `<p>Technology should address a defined educational problem rather than be adopted because it is novel.</p><ol><li>Define the learning need and intended outcome.</li><li>Select the simplest suitable technology.</li><li>Align the activity with assessment.</li><li>Protect accessibility, privacy, and fairness.</li><li>Pilot, pre-brief, facilitate, debrief, and evaluate.</li><li>Refine or discontinue the intervention according to evidence.</li></ol>`,
    },
    "zh-hant": {
      label: "學習科技",
      eyebrow: "學習設計",
      title: "運用科技促進教與學",
      body: `<p>採用科技應為了解決明確的教育問題，而不是因為科技新穎。</p><ol><li>界定學習需要及預期成果。</li><li>選擇最簡單而合適的科技。</li><li>使學習活動與評估互相配合。</li><li>保障無障礙使用、私隱及公平。</li><li>進行試行、事前簡介、引導、解說及評估。</li><li>根據證據改良或停止介入措施。</li></ol>`,
    },
    "zh-hans": {
      label: "学习科技",
      eyebrow: "学习设计",
      title: "运用科技促进教与学",
      body: `<p>采用科技应为了解决明确的教育问题，而不是因为科技新颖。</p><ol><li>界定学习需要及预期成果。</li><li>选择最简单而合适的科技。</li><li>使学习活动与评估相互配合。</li><li>保障无障碍使用、隐私及公平。</li><li>进行试行、事前简介、引导、复盘及评估。</li><li>根据证据改进或停止干预措施。</li></ol>`,
    },
  }),
  note("ai-foundations", "technology", "technology", {
    en: {
      label: "AI foundations",
      eyebrow: "Artificial intelligence",
      title: "AI Foundations and Educational Use",
      body: `<p>AI includes machine learning, neural networks, natural-language processing, and computer vision. Educational benefits must be considered alongside limitations.</p><h3>Responsible use</h3><ul><li>Build AI literacy before expecting effective use.</li><li>Require transparency and appropriate disclosure.</li><li>Protect personal, sensitive, confidential, and copyrighted information.</li><li>Review outputs for inaccuracy, fabrication, bias, and missing context.</li><li>Keep students and researchers accountable for final work.</li><li>Use AI-content detection cautiously and never as definitive proof by itself.</li></ul>`,
    },
    "zh-hant": {
      label: "人工智能基礎",
      eyebrow: "人工智能",
      title: "人工智能基礎與教育應用",
      body: `<p>人工智能包括機器學習、神經網絡、自然語言處理及電腦視覺。評估教育效益時亦須考慮其限制。</p><h3>負責任使用</h3><ul><li>先建立人工智能素養，才期望使用者有效運用。</li><li>要求透明度及適當披露。</li><li>保護個人、敏感、機密及受版權保護的資料。</li><li>檢視輸出有否錯誤、虛構、偏見或欠缺脈絡。</li><li>學生與研究人員仍須為最終作品負責。</li><li>審慎使用人工智能內容偵測，且不可把結果視為單一確證。</li></ul>`,
    },
    "zh-hans": {
      label: "人工智能基础",
      eyebrow: "人工智能",
      title: "人工智能基础与教育应用",
      body: `<p>人工智能包括机器学习、神经网络、自然语言处理及计算机视觉。评估教育效益时也须考虑其限制。</p><h3>负责任使用</h3><ul><li>先建立人工智能素养，才期望使用者有效运用。</li><li>要求透明度及适当披露。</li><li>保护个人、敏感、机密及受版权保护的信息。</li><li>检查输出是否存在错误、虚构、偏见或缺少语境。</li><li>学生与研究人员仍须为最终作品负责。</li><li>谨慎使用人工智能内容检测，且不可把结果视为单一确证。</li></ul>`,
    },
  }),
  note("generative-ai", "technology education", "technology", {
    en: {
      label: "Generative AI",
      eyebrow: "Generative AI",
      title: "Generative AI in Teaching and Learning",
      body: `<p>Generative AI is most educationally useful when it augments human thinking rather than substitutes for it.</p><ul><li><strong>Throwing:</strong> asking for a quick answer with little direction.</li><li><strong>Flipping:</strong> asking AI to question the learner and stimulate thought.</li><li><strong>Directing:</strong> specifying the task, context, standards, and intended outcome.</li></ul><p>Learners should plan, iterate, evaluate, disclose material AI use, and remain responsible for accuracy, reasoning, and voice. The first response is material for review, not a finished product.</p>`,
    },
    "zh-hant": {
      label: "生成式人工智能",
      eyebrow: "生成式人工智能",
      title: "生成式人工智能在教與學中的應用",
      body: `<p>生成式人工智能最具教育價值之處，是增強人的思考，而不是取代思考。</p><ul><li><strong>投擲式：</strong>只給予少量指示並要求快速答案。</li><li><strong>反轉式：</strong>要求人工智能向學習者提問並刺激思考。</li><li><strong>指導式：</strong>清楚說明任務、脈絡、標準及預期成果。</li></ul><p>學習者應規劃、反覆改進、評估、披露實質的人工智能使用，並為準確性、推理及個人聲音負責。首次輸出是待檢視的材料，而不是完成品。</p>`,
    },
    "zh-hans": {
      label: "生成式人工智能",
      eyebrow: "生成式人工智能",
      title: "生成式人工智能在教与学中的应用",
      body: `<p>生成式人工智能最具教育价值之处，是增强人的思考，而不是取代思考。</p><ul><li><strong>投掷式：</strong>只给予少量指示并要求快速答案。</li><li><strong>反转式：</strong>要求人工智能向学习者提问并激发思考。</li><li><strong>指导式：</strong>清楚说明任务、语境、标准及预期成果。</li></ul><p>学习者应规划、反复改进、评估、披露实质的人工智能使用，并为准确性、推理及个人声音负责。首次输出是待检查的材料，而不是完成品。</p>`,
    },
  }),
  note("research-integrity", "technology research", "research", {
    en: {
      label: "Research integrity",
      eyebrow: "Research integrity",
      title: "Research Integrity in the Generative AI Era",
      body: `<p>AI can function as a preliminary reviewer by identifying unclear arguments, missing context, and possible weaknesses.</p><ul><li>Disclose material AI contribution.</li><li>Verify every source, analysis, and generated claim.</li><li>Do not expose confidential manuscripts or data to unauthorised systems.</li><li>Treat AI feedback as advisory and challenge it where necessary.</li><li>Do not delegate novelty, methods, interpretation, or research accountability.</li></ul>`,
    },
    "zh-hant": {
      label: "研究誠信",
      eyebrow: "研究誠信",
      title: "生成式人工智能時代的研究誠信",
      body: `<p>人工智能可擔任初步審閱者，協助辨識論點不清、脈絡不足及可能的弱點。</p><ul><li>披露具實質影響的人工智能貢獻。</li><li>核實每項資料來源、分析及生成的主張。</li><li>不可把機密稿件或數據交予未獲授權的系統。</li><li>把人工智能回饋視為建議，並在需要時提出質疑。</li><li>不可把創新性、方法、詮釋或研究責任交由人工智能承擔。</li></ul>`,
    },
    "zh-hans": {
      label: "研究诚信",
      eyebrow: "研究诚信",
      title: "生成式人工智能时代的研究诚信",
      body: `<p>人工智能可担任初步审阅者，帮助识别论点不清、语境不足及可能的弱点。</p><ul><li>披露具有实质影响的人工智能贡献。</li><li>核实每项信息来源、分析及生成的主张。</li><li>不可把机密稿件或数据交给未获授权的系统。</li><li>把人工智能反馈视为建议，并在需要时提出质疑。</li><li>不可把创新性、方法、解释或研究责任交由人工智能承担。</li></ul>`,
    },
  }),
  note("productive-struggle", "education technology", "education", {
    en: {
      label: "Productive struggle",
      eyebrow: "Teaching and learning",
      title: "Productive Struggle and the Safe Bubble",
      body: `<p>A supportive learning environment should not remove every challenge. The educational task is to distinguish between unnecessary barriers and the kinds of difficulty that help students build judgement, resilience, and professional independence.</p><ul><li>Ask students to attempt the problem before using AI.</li><li>Use AI output as material for critique rather than as a finished answer.</li><li>Make students explain what they accepted, rejected, and changed.</li><li>Preserve some tasks where memory, reasoning, communication, and practical performance must be demonstrated without AI assistance.</li><li>Distinguish compassionate support from over-protection.</li></ul>`,
    },
    "zh-hant": {
      label: "有效掙扎",
      eyebrow: "教與學",
      title: "有效掙扎與安全泡泡",
      body: `<p>具支持性的學習環境不應移除所有挑戰。教育者需要區分不必要的障礙，以及能幫助學生建立判斷、韌性與專業獨立性的困難。</p><ul><li>要求學生先自行嘗試，再使用人工智能。</li><li>把人工智能輸出當作批判材料，而不是完成答案。</li><li>要求學生說明自己接受、拒絕和修改了甚麼。</li><li>保留部分必須在沒有人工智能協助下展示記憶、推理、溝通及實務表現的任務。</li><li>區分具同理心的支援與過度保護。</li></ul>`,
    },
    "zh-hans": {
      label: "有效挣扎",
      eyebrow: "教与学",
      title: "有效挣扎与安全泡泡",
      body: `<p>具支持性的学习环境不应移除所有挑战。教育者需要区分不必要的障碍，以及能帮助学生建立判断、韧性与专业独立性的困难。</p><ul><li>要求学生先自行尝试，再使用人工智能。</li><li>把人工智能输出当作批判材料，而不是完成答案。</li><li>要求学生说明自己接受、拒绝和修改了什么。</li><li>保留部分必须在没有人工智能协助下展示记忆、推理、沟通及实践表现的任务。</li><li>区分具同理心的支持与过度保护。</li></ul>`,
    },
  }),
  note("vr-design", "technology education", "technology", {
    en: {
      label: "VR design",
      eyebrow: "Virtual reality",
      title: "Virtual Reality Education Design Toolkit",
      body: `<p>VR should address a genuine learning need and provide value beyond a simpler teaching method.</p><ol><li>Identify the educational problem and target learners.</li><li>Align the activity with outcomes and assessment.</li><li>Define governance and stakeholder responsibilities.</li><li>Plan technical, spatial, and operational readiness.</li><li>Pre-brief learners and manage cognitive load.</li><li>Protect comfort, safety, withdrawal rights, accessibility, equity, and fairness.</li><li>Debrief, collect feedback, and refine iteratively.</li></ol>`,
    },
    "zh-hant": {
      label: "VR 設計",
      eyebrow: "虛擬實境",
      title: "虛擬實境教育設計工具",
      body: `<p>虛擬實境應回應真實的學習需要，並提供較簡單教學方法無法帶來的價值。</p><ol><li>辨識教育問題及目標學習者。</li><li>使活動與學習成果及評估互相配合。</li><li>界定管治安排及持份者責任。</li><li>規劃技術、空間及運作準備。</li><li>向學習者作事前簡介並管理認知負荷。</li><li>保障舒適、安全、退出權、無障礙使用、平等及公平。</li><li>進行解說、收集回饋並反覆改良。</li></ol>`,
    },
    "zh-hans": {
      label: "VR 设计",
      eyebrow: "虚拟现实",
      title: "虚拟现实教育设计工具",
      body: `<p>虚拟现实应回应真实的学习需要，并提供较简单教学方法无法带来的价值。</p><ol><li>识别教育问题及目标学习者。</li><li>使活动与学习成果及评估相互配合。</li><li>界定治理安排及利益相关者责任。</li><li>规划技术、空间及运行准备。</li><li>向学习者作事前简介并管理认知负荷。</li><li>保障舒适、安全、退出权、无障碍使用、平等及公平。</li><li>进行复盘、收集反馈并反复改进。</li></ol>`,
    },
  }),
  note("trexo", "physiotherapy technology", "physiotherapy", {
    en: {
      label: "Clinical technology",
      eyebrow: "Clinical technology",
      title: "Paediatric Exoskeleton: Educational Screening Overview",
      body: `<p>This public note records educational themes only and is not a clinical protocol or substitute for current manufacturer guidance, clinical assessment, or medical clearance.</p><ul><li>Confirm device-specific body measurements and fit.</li><li>Review joint range, alignment, hip status, tone, behaviour, bone health, recent surgery, and weight-bearing restrictions.</li><li>Confirm that the child can communicate pain or distress, including through non-verbal cues.</li><li>Escalate uncertain findings to appropriately qualified clinical and medical professionals.</li></ul>`,
    },
    "zh-hant": {
      label: "臨床科技",
      eyebrow: "臨床科技",
      title: "兒童外骨骼：教育用途篩查概覽",
      body: `<p>本公開筆記只記錄教育主題，並非臨床程序，亦不能取代最新製造商指引、臨床評估或醫療許可。</p><ul><li>確認裝置所需的身體量度及合適度。</li><li>檢視關節活動幅度、排列、髖關節狀況、肌張力、行為、骨骼健康、近期手術及負重限制。</li><li>確認兒童能以言語或非言語訊號表達疼痛或不適。</li><li>把不確定的發現轉介予具適當資格的臨床及醫療專業人員。</li></ul>`,
    },
    "zh-hans": {
      label: "临床科技",
      eyebrow: "临床科技",
      title: "儿童外骨骼：教育用途筛查概览",
      body: `<p>本公开笔记只记录教育主题，并非临床流程，也不能取代最新制造商指南、临床评估或医疗许可。</p><ul><li>确认设备所需的身体测量及适配情况。</li><li>检查关节活动范围、排列、髋关节状况、肌张力、行为、骨骼健康、近期手术及负重限制。</li><li>确认儿童能以语言或非语言信号表达疼痛或不适。</li><li>把不确定的发现转介给具适当资格的临床及医疗专业人员。</li></ul>`,
    },
  }),
  note("para-sport", "physiotherapy research", "physiotherapy", {
    en: {
      label: "Para-sport",
      eyebrow: "Sport and research",
      title: "Para-sport Reaction and Cognitive Testing",
      body: `<p>Reaction testing may examine simple responses, choices between responses, or more complex processing of competing information.</p><p>Possible tools include flanker paradigms, Corsi block tasks, the Tower of London, block design, and matrix reasoning. Test selection should follow the research question and account for athlete classification, communication, sensory access, and motor requirements. General cognitive tests should not be treated simplistically as measures of sporting intelligence.</p>`,
    },
    "zh-hant": {
      label: "殘疾人運動",
      eyebrow: "運動與研究",
      title: "殘疾人運動的反應與認知測試",
      body: `<p>反應測試可評估簡單反應、反應選擇，或處理互相競爭資訊的複雜過程。</p><p>可考慮的工具包括側抑制任務、Corsi 方塊任務、倫敦塔、積木設計及矩陣推理。測試選擇應以研究問題為依據，並考慮運動員分級、溝通、感官使用及動作要求。不應把一般認知測試簡化為運動智力的量度。</p>`,
    },
    "zh-hans": {
      label: "残疾人运动",
      eyebrow: "运动与研究",
      title: "残疾人运动的反应与认知测试",
      body: `<p>反应测试可评估简单反应、反应选择，或处理相互竞争信息的复杂过程。</p><p>可考虑的工具包括侧抑制任务、Corsi 方块任务、伦敦塔、积木设计及矩阵推理。测试选择应以研究问题为依据，并考虑运动员分级、沟通、感官使用及动作要求。不应把一般认知测试简化为运动智力的测量。</p>`,
    },
  }),
  note("ai-physio", "research technology physiotherapy", "research", {
    en: {
      label: "AI + physiotherapy",
      eyebrow: "Research digest",
      title: "AI in Physiotherapy Education",
      body: `<p>Direct evidence about generative AI in physiotherapy education remains limited. The defensible approach is to use AI as a supervised thinking partner while preserving observation, communication, practical examination, and accountable clinical judgement.</p><h3>Possible teaching applications</h3><ul><li>Ask students to critique an imperfect AI-generated assessment or treatment plan.</li><li>Require an initial judgement before AI consultation, followed by comparison and reflection.</li><li>Review and rewrite AI-generated patient education for accuracy, safety, and person-centred communication.</li><li>Use AI to vary simulation cases within educator-controlled boundaries.</li><li>Require disclosure of the tool, purpose, verification, and student contribution.</li></ul><p>The core sequence is: reason, consult, challenge, decide, and reflect.</p>`,
    },
    "zh-hant": {
      label: "人工智能與物理治療",
      eyebrow: "研究摘要",
      title: "人工智能在物理治療教育中的應用",
      body: `<p>有關生成式人工智能在物理治療教育中的直接證據仍然有限。較穩妥的做法，是把人工智能用作受監督的思考伙伴，同時保留觀察、溝通、實務檢查及可問責的臨床判斷。</p><h3>可能的教學應用</h3><ul><li>要求學生批判有缺陷的人工智能生成評估或治療計劃。</li><li>先作初步判斷，再諮詢人工智能，然後進行比較與反思。</li><li>檢視並重寫人工智能生成的病人教育內容，以確保準確、安全及以人為本的溝通。</li><li>在教師控制的範圍內，運用人工智能改變模擬個案。</li><li>要求披露所用工具、目的、核實過程及學生貢獻。</li></ul><p>核心次序是：推理、諮詢、質疑、決定及反思。</p>`,
    },
    "zh-hans": {
      label: "人工智能与物理治疗",
      eyebrow: "研究摘要",
      title: "人工智能在物理治疗教育中的应用",
      body: `<p>有关生成式人工智能在物理治疗教育中的直接证据仍然有限。较稳妥的做法，是把人工智能用作受监督的思考伙伴，同时保留观察、沟通、实践检查及可问责的临床判断。</p><h3>可能的教学应用</h3><ul><li>要求学生批判有缺陷的人工智能生成评估或治疗计划。</li><li>先作初步判断，再咨询人工智能，然后进行比较与反思。</li><li>检查并重写人工智能生成的患者教育内容，以确保准确、安全及以人为本的沟通。</li><li>在教师控制的范围内，运用人工智能改变模拟案例。</li><li>要求披露所用工具、目的、核实过程及学生贡献。</li></ul><p>核心顺序是：推理、咨询、质疑、决定及反思。</p>`,
    },
  }),
  note("ai-policy-pressure", "technology research education", "research", {
    en: {
      label: "AI policy pressure",
      eyebrow: "AI governance",
      title: "AI Policy and Academic Integrity Pressure",
      body: `<p>University AI policy matters, but policy alone is not enough. Students make decisions about AI under pressure from grades, deadlines, peer norms, and online misinformation.</p><ul><li>State AI permissions clearly for each assessment.</li><li>Require process, verification, sources, and student contribution where AI use is allowed.</li><li>Use flawed AI outputs as teaching material.</li><li>Discuss peer pressure and misinformation directly.</li><li>Assess reasoning, defence, and process rather than only the final artefact.</li></ul>`,
    },
    "zh-hant": {
      label: "人工智能政策壓力",
      eyebrow: "人工智能管治",
      title: "人工智能政策與學術誠信壓力",
      body: `<p>大學的人工智能政策很重要，但政策本身並不足夠。學生往往在成績、期限、同儕規範及網上錯誤資訊的壓力下決定如何使用人工智能。</p><ul><li>為每項評估清楚說明人工智能是否可用。</li><li>在允許使用人工智能時，要求交代過程、核實、來源及學生貢獻。</li><li>把有缺陷的人工智能輸出用作教學材料。</li><li>直接討論同儕壓力與錯誤資訊。</li><li>評估推理、辯護與過程，而不只看最終成品。</li></ul>`,
    },
    "zh-hans": {
      label: "人工智能政策压力",
      eyebrow: "人工智能治理",
      title: "人工智能政策与学术诚信压力",
      body: `<p>大学的人工智能政策很重要，但政策本身并不足够。学生往往在成绩、期限、同伴规范及网上错误信息的压力下决定如何使用人工智能。</p><ul><li>为每项评估清楚说明人工智能是否可用。</li><li>在允许使用人工智能时，要求交代过程、核实、来源及学生贡献。</li><li>把有缺陷的人工智能输出用作教学材料。</li><li>直接讨论同伴压力与错误信息。</li><li>评估推理、辩护与过程，而不只看最终成品。</li></ul>`,
    },
  }),
  note("ai-acceleration", "technology research", "research", {
    en: {
      label: "Academic workflows",
      eyebrow: "Academic work",
      title: "AI and the Acceleration of Academic Work",
      body: `<p>AI does not simply save time. In academic institutions, efficiency gains are often absorbed into higher output expectations, shifting the real bottleneck toward judgement, direction, and accountability.</p><ul><li>The key question is not only whether AI was allowed, but whether the user can account for each decision.</li><li>Expert users can direct AI outputs critically; novice users may bypass the struggle needed to develop expertise.</li><li>Assessment and supervision should focus more on reasoning, trade-offs, and defensible choices.</li><li>Reflective AI-use statements should explain judgement, not only prompts.</li></ul>`,
    },
    "zh-hant": {
      label: "學術工作流程",
      eyebrow: "學術工作",
      title: "人工智能與學術工作的加速",
      body: `<p>人工智能並不只是節省時間。在學術環境中，效率提升往往會被更高的產出期望吸收，真正的瓶頸反而轉向判斷、方向與問責。</p><ul><li>關鍵問題不只是是否容許使用人工智能，而是使用者能否為每個決定負責。</li><li>專家能較有批判地引導人工智能輸出；初學者則可能繞過建立專業能力所需的掙扎。</li><li>評估與督導應更重視推理、取捨與可辯護的選擇。</li><li>人工智能使用反思應說明判斷，而不只是提示語。</li></ul>`,
    },
    "zh-hans": {
      label: "学术工作流程",
      eyebrow: "学术工作",
      title: "人工智能与学术工作的加速",
      body: `<p>人工智能并不只是节省时间。在学术环境中，效率提升往往会被更高的产出期望吸收，真正的瓶颈反而转向判断、方向与问责。</p><ul><li>关键问题不只是是否允许使用人工智能，而是使用者能否为每个决定负责。</li><li>专家能更有批判性地引导人工智能输出；初学者则可能绕过建立专业能力所需的挣扎。</li><li>评估与督导应更重视推理、取舍与可辩护的选择。</li><li>人工智能使用反思应说明判断，而不只是提示词。</li></ul>`,
    },
  }),
];
