// Lecturer-editable landmarks (SVG coordinates). Verify against the programme's taught protocol.
const ANTERIOR_AUSCULTATION_SITES = [
  { x: 405, y: 178, label: "Left upper zone", instruction: "Place the stethoscope over the patient's left upper anterior zone.", pairInstruction: "Place the stethoscope over either upper anterior zone.", hint: "In this front view, the patient's left is on your right. Begin below the clavicle and away from the sternum.", pairHint: "Begin below either clavicle and away from the sternum.", correct: "Correct. Compare with the equivalent upper zone on the other side." },
  { x: 315, y: 178, label: "Right upper zone", instruction: "Compare at the matching upper anterior zone on the opposite side.", hint: "Keep the chestpiece at the same horizontal level.", correct: "Correct. The upper pair is complete; continue to the middle zones." },
  { x: 420, y: 286, label: "Left middle zone", instruction: "Move to the patient's left middle anterior zone.", pairInstruction: "Move to either middle anterior zone.", hint: "Move inferiorly and slightly laterally.", pairHint: "Choose either side, moving inferiorly and slightly laterally from the upper zones." },
  { x: 300, y: 286, label: "Right middle zone", instruction: "Compare at the matching middle anterior zone on the opposite side.", hint: "Compare side to side before moving down.", correct: "Correct. The middle pair is complete; continue to the lower zones." },
  { x: 434, y: 400, label: "Left lower zone", instruction: "Place the stethoscope over the patient's left lower anterior zone.", pairInstruction: "Place the stethoscope over either lower anterior zone.", hint: "Move inferiorly while remaining over an intercostal space.", pairHint: "Choose either lower zone, remaining over an intercostal space." },
  { x: 286, y: 400, label: "Right lower zone", instruction: "Compare at the matching lower anterior zone on the opposite side.", hint: "Match the level of the previous site.", correct: "Correct. The lower pair is complete; continue to the axillary sites." },
  { x: 500, y: 322, label: "Left axilla", instruction: "Move to the patient's left axillary site.", pairInstruction: "Move to either axillary site.", hint: "Move laterally beneath the axilla while keeping the chestpiece on the thorax.", pairHint: "Choose either side beneath the axilla while keeping the chestpiece on the thorax." },
  { x: 220, y: 322, label: "Right axilla", instruction: "Finish at the matching axillary site on the opposite side.", hint: "Complete the assessment at the equivalent level on the other side.", correct: "Correct. Both axillary sites are complete." }
];
CardioGame.initPlacementGame({gameId:"cardio-auscultation-anterior",view:"anterior",start:{x:620,y:480},tolerance:38,points:ANTERIOR_AUSCULTATION_SITES,pairedSequence:true,completeTitle:"Anterior sequence complete",completionMetric:"Sites completed",startFeedback:"Start at either upper anterior zone and compare equivalent positions side to side.",generalHint:"Use a systematic side-to-side sequence, then complete the matched axillary sites."});
